import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const templates = [
  {
    tema: 'Lingkungan Sekitarku',
    topikKBC: 'Cinta Diri dan Sesama',
    profilLulusan: 'Kesehatan, Kemandirian, Bernalar Kritis, Kreatif, Berkarakter, Beriman, Bertakwa',
    tujuanKBC: 'Mengenal mesjid sebagai tempat ibadah umat Islam dan memahami cara bersikap yang tepat di dalamnya. Anak diajak untuk mencintai tempat ibadah, memahami fungsi mesjid dalam kehidupan muslim, dan membiasakan diri dengan adab-adab yang harus dijaga saat berada di dalam mesjid. Melalui kegiatan ini, anak diharapkan tumbuh dengan rasa cinta dan hormat terhadap rumah Allah, memahami bahwa mesjid adalah tempat yang mulia dan sakral, serta menumbuhkan kebiasaan baik sejak dini untuk selalu menjaga kebersihan dan ketertiban di tempat ibadah.',
    tujuanProfilLulusan: {
      Kesehatan: 'Mengenal dan memahami lingkungan yang sehat di sekitar mesjid, termasuk menjaga kebersihan tempat ibadah, memahami pentingnya berwudhu sebelum beribadah, dan menjaga kesehatan fisik saat beraktivitas di lingkungan mesjid. Anak belajar bahwa kebersihan adalah sebagian dari iman dan bahwa menjaga tubuh tetap bersih saat berada di mesjid adalah bentuk rasa hormat kepada Allah.',
      Kemandirian: 'Dapat merawat diri sendiri saat berada di mesjid, mulai dari cara memakai pakaian yang sopan dan menutup aurat, cara berwudhu dengan benar dan mandiri, mengatur benda-benda pribadi seperti tasbih dan mukena, serta mempraktikkan tata cara salat secara mandiri dengan bimbingan guru yang minim. Anak dilatih untuk tidak bergantung pada orang dewasa dalam hal-hal dasar ibadah.',
      BernalarKritis: 'Memahami alasan mengapa harus berperilaku baik di mesjid, menganalisis fungsi setiap bagian mesjid seperti mihrab, mimbar, dan saf salat, mempertanyakan dan mencari jawaban tentang mengapa mesjid dianggap sakral dan harus dijaga kehormatannya, serta memahami makna gerakan-gerakan salat yang dilakukan dan hikmah di baliknya.',
      Kreatif: 'Menciptakan aktivitas bermain yang sesuai dengan lingkungan mesjid, membuat karya seni bertema mesjid dengan berbagai bahan dan teknik, bermain peran sebagai orang yang sedang beribadah di mesjid dengan ekspresi yang tepat, menemukan cara-cara baru untuk menjaga kebersihan dan ketertiban mesjid, serta berinovasi dalam menggambarkan keindahan mesjid.',
      Berkarakter: 'Menumbuhkan sikap hormat dan sopan di tempat ibadah, belajar untuk diam dan mendengarkan saat ceramah atau khotbah berlangsung, menghargai orang lain yang sedang beribadah dengan tidak membuat gangguan, serta mempraktikkan nilai-nilai kasih sayang dan kepedulian terhadap sesama jamaah mesjid. Anak belajar bahwa mesjid adalah tempat untuk kedamaian dan kebersamaan.',
      Beriman: 'Mengenal mesjid sebagai tempat untuk mendekatkan diri kepada Allah SWT, memahami bahwa mesjid adalah rumah Allah yang harus disegani dan dicintai, merasakan kedamaian dan ketenangan saat berada di dalam mesjid, serta mulai memahami konsep ibadah sebagai bentuk ketaatan dan cinta kepada Allah yang menciptakan kita.',
      Bertakwa: 'Mengenal dasar-dasar ibadah yang dilakukan di mesjid seperti salat, dzikir, dan mendengarkan ceramah agama, mempraktikkan gerakan salat dasar dengan benar dan penuh penghayatan sesuai dengan kemampuan usia dini, memahami bacaan-bacaan dasar dalam salat seperti Takbir, Al-Fatihah, dan sujud, serta membiasakan diri untuk datang ke mesjid sebagai bentuk taat kepada Allah.'
    },
    tujuanPembelajaranMendalam: 'KD1: Mengenal mesjid dan fungsi sebagai tempat ibadah umat Islam untuk mendekatkan diri kepada Allah SWT serta memahami peran mesjid dalam kehidupan komunitas Muslim.\nKD2: Memahami cara bersikap sopan dan hormat di mesjid sesuai dengan adab Islam, termasuk cara berjalan, berbicara, dan berpakaian yang sesuai di tempat ibadah.\nKD3: Mengenal aktivitas ibadah yang dilakukan di mesjid seperti salat berjamaah, dzikir, mendengarkan ceramah, dan membaca Al-Quran.\nKD4: Mempraktikkan gerakan salat dasar dengan benar termasuk berdiri, rukuk, sujud, dan duduk di antara dua sujud.\nKD5: Memahami bagian-bagian penting mesjid seperti mihrab, mimbar, saf, dan kubah beserta fungsinya masing-masing.\nKD6: Memahami makna dan fungsi wudhu sebagai syarat sahnya salat dan cara melaksanakannya dengan benar.\nKD7: Menumbuhkan rasa cinta dan bangga terhadap mesjid sebagai rumah Allah dan tempat berkumpulunya umat Islam.',
    materiIntegrasiKBC: 'Pengenalan mesjid sebagai rumah Allah dan tempat ibadah umat Islam, fungsi mesjid dalam kehidupan masyarakat muslim sebagai pusat ibadah, pendidikan, dan sosial, adab dan tata tertib di dalam mesjid yang harus dipatuhi setiap Muslim, aktivitas ibadah yang dilakukan di mesjid mulai dari salat, dzikir, hingga ceramah, makna dan fungsi wudhu sebagai pembersih sebelum ibadah, bagian-bagian mesjid seperti mihrab tempat imam memimpin salat, mimbar tempat khotbah, saf untuk shaf, menara untuk adzan, dan kubah sebagai atap, bacaan-bacaan dasar dalam salat seperti Takbiratul Ihram, Al-Fatihah, dan salam, gerakan-gerakan salat beserta makna dan hikmahnya, konsep salat berjamaah dan keutamaannya dibanding salat sendiri, sejarah singkat pembangunan mesjid pertama di Islam yaitu Masjid Quba dan Masjid Nabawi, serta makna kebersihan sebagian dari iman.',
    tujuanPembelajaran: 'Setelah mengikuti kegiatan pembelajaran ini, anak diharapkan dapat: (1) Mengenal mesjid sebagai tempat ibadah umat Islam dan rumah Allah SWT, (2) Memahami fungsi mesjid dalam kehidupan seorang Muslim sebagai pusat ibadah dan sosial, (3) Menjelaskan cara bersikap yang sopan dan hormat saat berada di dalam mesjid sesuai adab Islam, (4) Mempraktikkan adab-adab yang harus dijaga di mesjid seperti menjaga kebersihan, berbicara pelan, dan tidak bermain-main saat salat, (5) Mengenal bagian-bagian mesjid seperti mihrab, mimbar, saf, menara, dan kubah beserta fungsinya, (6) Mempraktikkan gerakan salat dasar dengan benar dan penuh penghayatan, (7) Memahami pentingnya wudhu sebelum salat dan cara melaksanakannya, (8) Menumbuhkan rasa cinta dan bangga terhadap mesjid sebagai rumah Allah, (9) Menunjukkan sikap hormat dan kasih sayang terhadap tempat ibadah dan jamaah lainnya, dan (10) Membiasakan diri untuk datang ke mesjid untuk beribadah bersama keluarga dan komunitas.',
    kerangkaPembelajaran: {
      praktekPedagogik: 'Pembelajaran berbasis pengalaman langsung melalui kunjungan ke mesjid untuk observasi nyata, main peran untuk mempraktikkan aktivitas ibadah di mesjid dengan ekspresi yang tepat, observasi lapangan untuk mengenal bagian-bagian mesjid dan fungsinya secara langsung, cerita bergambar tentang sejarah dan keindahan mesjid untuk menumbuhkan rasa cinta, pertanyaan terbuka untuk merangsang berpikir kritis anak tentang pentingnya mesjid, pembelajaran berbasis proyek untuk membuat miniatur mesjid dan karya seni lainnya, pembiasaan adab melalui praktik langsung dengan bimbingan yang konsisten, dan diskusi kelompok untuk berbagi pengalaman tentang mesjid.',
      lingkunganPembelajaran: {
        fisik: 'Model mesjid mini yang detail dan realistis dengan bagian-bagian lengkap seperti mihrab, mimbar, menara, dan kubah, gambar-gambar mesjid dari berbagai sudut dan bagian-bagiannya untuk visualisasi, karpet sholat atau alas untuk praktik salat yang nyaman dan aman untuk anak, alat-alat salat seperti sajadah mini untuk setiap anak, tasbih untuk pengenalan dzikir, mukena mini untuk anak perempuan, poster tentang adab di mesjid dengan gambar ilustrasi yang jelas, dan sudut baca dengan buku cerita tentang mesjid dan Islam.',
        sosial: 'Kerja kelompok kecil untuk proyek pembuatan karya mesjid yang melatih kerja sama dan komunikasi, interaksi langsung dengan pengurus masjid atau orang tua yang berpengalaman untuk penjelasan lebih mendalam, bermain bersama teman dalam simulasi salat berjamaah untuk melatih kerja sama dan kebersamaan, saling membantu saat praktik wudhu dan salat untuk menumbuhkan kepedulian, diskusi kelompok untuk berbagi pengalaman dan pengetahuan tentang mesjid, dan presentasi hasil karya di depan teman-teman untuk melatih kepercayaan diri.',
        psikologis: 'Lingkungan yang nyaman, aman, dan mendukung untuk eksplorasi tanpa rasa takut atau cemas, pujian dan motivasi positif untuk setiap usaha dan keberanian anak dalam mencoba hal baru, ruang untuk berekspresi kreativitas tanpa takut salah atau dikritik keras, suasana yang hangat dan penuh kasih sayang dari guru dan teman-teman, dan penghargaan terhadap perbedaan kemampuan dan kecepatan belajar setiap anak.',
        akademik: 'Buku cerita bergambar tentang mesjid dan sejarahnya yang sesuai usia dini, gambar-gambar detail tentang aktivitas ibadah di mesjid dengan keterangan yang jelas, video edukasi pendek tentang salat dan wudhu untuk visualisasi, kartu-kartu kata tentang nama bagian mesjid untuk pengenalan kosakata, dan bahan bacaan sederhana tentang adab di mesjid yang mudah dipahami anak.'
      },
      kemitraanPembelajaran: 'Orang tua untuk mendampingi anak dalam mengenal mesjid dan memperkuat pembelajaran di rumah, pengurus masjid setempat untuk memberikan penjelasan langsung dan memperbolehkan kunjungan, tokoh agama atau ustaz untuk berbagi pengetahuan tentang mesjid dan ibadah, dan komunitas sekitar untuk mendukung kegiatan pembelajaran berbasis masyarakat.',
      pemanfaatanDigital: 'Video singkat dan animasi tentang mesjid dan aktivitas ibadah di dalamnya yang menarik untuk anak, aplikasi edukasi anak tentang belajar salat dan wudhu dengan interaktif, gambar-gambar digital dari berbagai mesjid di dunia untuk memperluas wawasan, dan audio bacaan salat untuk pengenalan suara yang benar.'
    },
    kegiatanPembelajaran: {
      persiapan: {
        pemahamanKonsep: 'Guru membaca buku cerita tentang mesjid dan mempelajari sejarah serta fungsi mesjid dalam Islam secara mendalam, guru menonton video pendek tentang kegiatan di mesjid untuk mendapatkan gambaran aktivitas yang akan diajarkan, guru berdiskusi dengan rekan sejawat tentang strategi terbaik untuk mengenalkan mesjid kepada anak usia dini, guru menyiapkan pertanyaan-pertanyaan pemantik sederhana namun mendalam tentang pengalaman anak dengan mesjid, dan guru menyiapkan contoh-contoh konkret dari kehidupan sehari-hari yang berkaitan dengan mesjid.',
        penyiapanAlat: 'Guru mempersiapkan model mesjid mini yang lengkap dengan semua bagian pentingnya untuk visualisasi yang baik, guru menyiapkan gambar-gambar besar tentang aktivitas di mesjid dengan keterangan yang jelas, guru mempersiapkan alat peraga salat seperti sajadah mini, tasbih, dan mukena untuk praktik langsung, guru menyiapkan area untuk praktik salat dan wudhu yang aman dan nyaman untuk anak, guru mempersiapkan bahan-bahan seni untuk membuat karya bertema mesjid dengan variasi yang menarik, dan guru mempersiapkan poster atau kartu tentang adab di mesjid untuk penguatan visual.',
        alatBahan: 'Kertas warna berbagai ukuran dan tebal untuk membuat karya seni, gunting aman untuk anak usia dini dengan pegangan yang mudah, lem non-toxic yang aman untuk anak, stiker bertema Islam dan mesjid untuk dekorasi karya, gambar mesjid dari berbagai sudut dan bagian-bagiannya untuk referensi dan kolase, model mesjid mini yang detail dan kokoh untuk observasi dan inspirasi, karpet atau alas salat yang bersih untuk praktik, sajadah mini untuk setiap anak dengan warna berbeda-beda, tasbih besar untuk demonstrasi dan tasbih kecil untuk anak, mukena mini untuk anak perempuan dengan berbagai pilihan warna, wastafel atau ember air yang bersih untuk praktik wudhu, sabun cuci tangan yang lembut dan aman untuk kulit anak, handuk bersih untuk setiap anak untuk mengeringkan tangan, poster bergambar aktivitas hidup sehat di mesjid, kartu-kartu emotikon sederhana untuk refleksi perasaan anak, dan buku cerita tentang mesjid dengan ilustrasi yang menarik.'
      },
      pelaksanaan: {
        orientasi: 'Guru mengumpulkan murid di area yang telah disiapkan dan mengajak mereka duduk melingkar dengan posisi yang nyaman dan aman, guru membuka kegiatan dengan salam dan sapaan hangat sambil memperkenalkan diri dengan ramah, kemudian guru menyebutkan tema hari itu dengan antusias: "Hari ini kita akan belajar tentang mesjid, rumah Allah!", guru bertanya: "Siapa di sini yang pernah ke mesjid? Apa yang kalian lihat di sana?" dan memberi kesempatan beberapa murid untuk bercerita, guru mengajak murid menyentuh bagian tubuh tertentu seperti dada, tangan, dan kaki sambil bertanya: "Bagian mana yang kita gunakan saat salat?", dan guru menjelaskan secara sederhana bahwa kegiatan hari ini akan membantu tubuh menjadi kuat dan sehat, serta mengingatkan bahwa tubuh adalah anugerah dari Allah yang harus dijaga.',
        eksplorasi: 'Guru memperlihatkan model mesjid mini yang detail dan mengajak murid mengenal bagian-bagiannya satu per satu: "Ini mihrab, tempat imam memimpin salat" dan "Ini mimbar, tempat khotib berdiri memberikan ceramah", guru menunjukkan gambar-gambar besar dari berbagai sudut mesjid dan menjelaskan fungsinya, murid diajak melihat-lihat model mesjid secara berkelompok dengan bimbingan guru, guru mempraktikkan gerakan salat sederhana seperti berdiri, rukuk, dan sujud dengan demonstrasi yang jelas dan perlahan, murid diajak untuk menirukan gerakan tersebut dengan bimbingan yang sabar dan suportif, guru menjelaskan makna setiap gerakan dengan bahasa yang sederhana dan mudah dipahami anak usia dini, dan guru memperbolehkan anak bertanya tentang hal-hal yang ingin mereka ketahui tentang mesjid.',
        diskusi: 'Guru mengajak murid kembali duduk melingkar di area yang teduh dan nyaman, lalu meminta mereka memperhatikan perasaan tubuhnya setelah bergerak, guru bertanya: "Kenapa ya kita harus bersikap sopan di mesjid?" dan memberikan kesempatan murid menjawab dengan kata-kata mereka sendiri, guru memberi penjelasan sederhana bahwa ketika kita berada di tempat suci, kita harus menghormatinya dengan sikap yang baik, guru bertanya lagi: "Apa saja yang boleh dan tidak boleh kita lakukan di mesjid?" dan mencatat jawaban murid di papan atau kertas besar sebagai bahan refleksi bersama, dan guru mengaitkan jawaban murid dengan nilai-nilai Islam tentang kebersihan, kesopanan, dan kebersamaan.',
        kolaborasi: 'Guru membagi murid menjadi beberapa kelompok kecil dengan 3-4 anak per kelompok untuk kerja sama yang efektif, setiap kelompok diberi tugas untuk membangun mesjid mini bersama menggunakan kardus dan bahan seni yang tersedia, kelompok lain bermain peran sholat berjamaah di mana satu anak menjadi imam dan yang lainnya menjadi makmum dengan bergantian peran, kelompok lain membuat poster tentang adab di mesjid dengan gambar dan tulisan sederhana yang jelas, dan guru berkeliling ke setiap kelompok untuk memberikan bimbingan, dukungan, dan pujian atas usaha mereka.',
        refleksi: 'Guru mengajak murid duduk kembali dengan tenang di area yang nyaman, lalu melakukan beberapa gerakan peregangan ringan untuk membuat tubuh lebih rileks setelah banyak bergerak, guru meminta setiap murid memilih satu emotikon sederhana (senang, biasa saja, atau lelah) dan menempelkannya pada poster refleksi sebagai tanda bagaimana perasaan mereka setelah mengikuti kegiatan, beberapa murid diminta secara sukarela untuk menceritakan pengalamannya seperti "Saya senang bisa melompat tinggi" atau "Saya jadi haus dan butuh minum", guru menghubungkan pengalaman ini dengan rasa syukur kepada Allah karena telah memberikan tubuh yang sehat dan kuat, guru menjelaskan bahwa menjaga kesehatan tubuh adalah bagian penting dari mencintai diri sendiri dan bersyukur kepada Allah, dan guru menutup sesi dengan pertanyaan: "Apa yang akan kalian lakukan di rumah supaya tubuh tetap sehat?" dan mengulang beberapa jawaban murid seperti "Banyak bergerak", "Makan makanan sehat", "Minum air putih", dan "Tidur cukup".'
      },
      pembuatanKarya: {
        proses: 'Anak membuat gambar mesjid dengan krayon atau cat air dengan pemanduan guru untuk teknik dasar, anak mewarnai gambar aktivitas ibadah seperti orang sedang salat atau wudhu dengan warna-warna cerah dan menarik, anak membuat miniatur mesjid dari kardus bekas dengan bantuan guru untuk teknik konstruksi dasar, anak menempel stiker bertema Islam dan mesjid untuk dekorasi tambahan pada karya mereka, dan anak bebas berekspresi dengan berbagai teknik seni sesuai kreativitas dan kemampuan masing-masing.',
        hasil: 'Kumpulan gambar mesjid berwarna yang beragam dan kreatif menunjukkan imajinasi dan pemahaman anak, miniatur mesjid 3D dari kardus yang bisa dipajang di kelas sebagai bahan pembelajaran, poster tentang adab di mesjid yang berisi aturan-aturan sederhana dengan gambar ilustrasi yang jelas untuk diingat anak, hiasan dinding bertema mesjid yang bisa menghias kelas dan mengingatkan anak tentang pentingnya mesjid, dan dokumentasi foto anak saat sedang membuat karya sebagai bukti proses pembelajaran dan kemajuan mereka.'
      },
      presentasi: {
        persiapan: 'Guru membantu setiap anak menyiapkan karya hasil proyek mereka untuk ditampilkan dengan rapi dan menarik, guru membimbing anak membuat kalimat sederhana untuk menjelaskan karya mereka seperti "Ini gambar mesjid saya" atau "Saya membuat ini dengan warna-warna cerah", dan guru menyiapkan sudut pajang di kelas atau di koridor madrasah sebagai "Galeri Mesjid Kita" untuk menampilkan semua karya anak dengan cara yang terhormat.',
        pelaksanaan: 'Setiap anak diminta maju ke depan kelas satu per satu untuk menunjukkan karya mereka dengan dukungan dan dorongan guru, anak menceritakan karya yang mereka buat dengan bimbingan guru untuk melatih keberanian berbicara di depan orang lain, anak menjawab pertanyaan sederhana dari teman-teman tentang karya mereka dengan bantuan guru jika perlu, teman-teman lain memberikan applause dan pujian sebagai bentuk apresiasi dan dukungan, dan guru memberikan komentar positif spesifik untuk setiap karya untuk memotivasi dan menghargai usaha anak.'
      },
      refleksiAkhir: {
        refleksiGuru: 'Guru menilai pemahaman anak tentang mesjid melalui observasi selama kegiatan dan pertanyaan-pertanyaan yang diajukan, guru mengamati sikap anak saat menirukan aktivitas di mesjid untuk melihat sejauh mana mereka memahami maknanya, guru menilai kreativitas anak dalam membuat karya seni bertema mesjid dengan melihat orisinalitas dan usaha yang dilakukan, guru mencatat anak-anak yang masih memerlukan bimbingan tambahan untuk materi berikutnya, dan guru mengevaluasi efektivitas strategi pembelajaran yang digunakan dan merencanakan perbaikan untuk pertemuan selanjutnya.',
        refleksiAnak: 'Anak menceritakan apa yang paling mereka sukai dari kegiatan hari ini dengan jujur dan lugas, anak menyampaikan hal baru yang mereka pelajari tentang mesjid yang sebelumnya tidak mereka ketahui, anak menyampaikan kesulitan yang mereka hadapi saat membuat karya atau mempraktikkan aktivitas agar guru bisa membantu, anak mengekspresikan perasaan mereka setelah belajar tentang mesjid apakah senang, bangga, atau ingin mencoba lagi, dan anak menyebutkan apa yang ingin mereka lakukan atau pelajari lebih lanjut tentang mesjid di masa depan.'
      }
    }
  }
]

async function main() {
  console.log('Updating RPP Templates with more comprehensive content...')

  for (const template of templates) {
    try {
      await prisma.rPPTemplate.upsert({
        where: { tema: template.tema },
        update: template,
        create: {
          ...template,
          tujuanProfilLulusan: JSON.stringify(template.tujuanProfilLulusan),
          kerangkaPembelajaran: JSON.stringify(template.kerangkaPembelajaran),
          kegiatanPembelajaran: JSON.stringify(template.kegiatanPembelajaran),
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date()
        }
      })
      console.log(`✅ Template "${template.tema}" berhasil diperbarui`)
    } catch (error) {
      console.error(`❌ Gagal mengupdate template "${template.tema}":`, error)
    }
  }

  console.log('\n✅ Update selesai!')
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
