import { db } from '@/lib/db'
  {
    tema: "Mengenal Nama-Nama Allah (Asmaul Husna)",
    kelompokUsia: "B",
    topikKBC: "Beriman dan Berakhlak Mulia",
    profilLulusan: "Beriman dan Berakhlak Mulia, Berkebinekaan Global, Gotong Royong, Mandiri dan Kreatif, Bernalar Kritis, Sehat Jasmani dan Rohani, Warga Negara",
    tujuanKBC: "Anak dapat mengenal dan memahami nama-nama Allah yang indah dengan penuh cinta dan kagum, menumbuhkan rasa syukur dan kepercayaan kepada Allah, serta menerapkan nilai-nilai keteladanan dalam kehidupan sehari-hari melalui perilaku yang mencerminkan sifat-sifat terpuji Allah SWT.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak dapat menghafal dan memahami makna minimal 10 Asmaul Husna, menyebutkan nama Allah dengan penuh kekaguman dan hormat, serta meneladani sifat-sifat Allah dalam perilaku sehari-hari seperti: Ar-Rahman (Maha Pengasih) dengan bersikap ramah dan peduli kepada teman, Al-Karim (Maha Mulia) dengan bersikap sopan dan tawadhu, Al-Hakim (Maha Bijaksana) dengan mampu membedakan perbuatan baik dan buruk.",
      berkebinekaan_global: "Anak menghargai perbedaan dalam beribadah dan keyakinan teman-temannya, memahami bahwa Asmaul Husna adalah ajaran Islam sambil menghormati teman-teman dari latar belakang berbeda.",
      gotong_royong: "Anak membantu teman yang kesulitan menghafal Asmaul Husna, berbagi cerita tentang kebaikan yang pernah dialami, dan bekerja sama dalam kelompok untuk membuat karya seni yang menggambarkan Asmaul Husna.",
      mandiri_dan_kreatif: "Anak dapat menemukan sendiri contoh penerapan Asmaul Husna dalam kehidupan sehari-hari, membuat karya kreatif seperti poster atau lagu tentang Asmaul Husna, serta mempresentasikannya dengan percaya diri.",
      bernalar_kritis: "Anak dapat menganalisis dan menjelaskan mengapa Allah memiliki nama-nama yang indah, membandingkan sifat-sifat Allah dengan perilaku manusia, serta mengajukan pertanyaan-pertanyaan tentang makna Asmaul Husna.",
      sehat_jasmani_dan_rohani: "Anak menjaga kebersihan hati dan pikiran dengan selalu mengingat Allah, melakukan gerakan fisik yang lembut saat menyebutkan Asmaul Husna, serta menjaga kesehatan melalui perilaku sesuai ajaran Islam.",
      warga_negara: "Anak memahami dirinya sebagai bagian dari masyarakat yang beriman, menghormati perbedaan agama di lingkungannya, serta bersikap toleran dan damai dalam pergaulan sehari-hari."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran yang menyenangkan dan bermakna, anak akan:\n1. Mengenali dan menyebutkan minimal 10 nama Allah (Asmaul Husna) dengan benar dan lancar\n2. Memahami makna dasar dari setiap Asmaul Husna yang dipelajari dengan bahasa yang sederhana dan mudah dipahami\n3. Menyambungkan setiap nama Allah dengan perilaku nyata yang dapat diteladani dalam kehidupan sehari-hari\n4. Menghafal Asmaul Husna dengan metode yang menyenangkan melalui lagu, permainan, dan gerakan tubuh\n5. Mengungkapkan perasaan syukur dan cinta kepada Allah melalui doa, dzikir, dan pujian\n6. Menunjukkan perilaku yang mencerminkan sifat-sifat Allah seperti kasih sayang, keadilan, dan kebijaksanaan dalam interaksi dengan teman dan keluarga\n7. Membuat karya seni sederhana yang menggambarkan pemahaman tentang Asmaul Husna",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 1 hari (± 2 jam) dengan pendekatan Cinta (KBC) yang menekankan:\n- Pembelajaran terintegrasi antara kognitif, afektif, dan psikomotorik\n- Metode inkuiri dan eksplorasi untuk membangun pemahaman yang mendalam\n- Pembelajaran kolaboratif melalui kerja kelompok dan diskusi\n- Pengalaman langsung dan praktik nyata dalam kehidupan sehari-hari\n- Penilaian berkelanjutan yang berfokus pada proses dan hasil\n- Integrasi nilai-nilai Islam dalam setiap aktivitas pembelajaran\n- Pemanfaatan lingkungan belajar yang hangat, nyaman, dan penuh cinta",
    kegiatanPembelajaran: {
      pendahuluan: "Guru membuka pembelajaran dengan salam, senyuman, dan pelukan kasih sayang kepada setiap anak. Guru mengajak anak berdoa bersama dengan khusyuk dan penuh rasa syukur. Guru memutarkan lagu Asmaul Husna yang menyenangkan dan mengajak anak menyanyikan bersama sambil melakukan gerakan tangan yang sesuai. Guru memunculkan rasa ingin tahu dengan bertanya: 'Anak-anak, siapa yang tahu bahwa Allah punya nama-nama yang sangat indah? Siapa yang ingin tahu nama-nama Allah itu?' Guru menampilkan poster atau flashcard Asmaul Husna dan meminta anak menebak maknanya.",
      inti: [
        "EKSPLORASI: Guru membagikan kartu-kartu Asmaul Husna kepada setiap anak secara berpasangan. Anak diminta mendiskusikan dan mencari tahu makna dari nama Allah yang mereka pegang dengan bantuan buku cerita atau gambar ilustrasi. Setiap kelompok mempresentasikan hasil diskusi mereka di depan kelas dengan cara yang kreatif.",
        "ELABORASI: Guru menceritakan kisah-kisah teladan yang menunjukkan penerapan Asmaul Husna dalam kehidupan sehari-hari. Contoh: kisah tentang Ar-Rahman melalui cerita Nabi yang menyayangi anak yatim, kisah Al-Adl melalui cerita keadilan Nabi. Guru mengajak anak bermain peran (role play) untuk mempraktikkan sifat-sifat tersebut dalam situasi nyata.",
        "KONFIRMASI: Guru mengajak anak menghafal Asmaul Husna dengan metode bernyanyi dan gerakan tubuh yang menyenangkan. Setiap nama Allah dinyanyikan dengan melodi lagu yang familiar dan diikuti gerakan tangan yang menggambarkan maknanya. Guru memberikan penguatan positif dan apresiasi untuk setiap usaha anak.",
        "PRAKTIK: Guru mengajak anak membuat 'Buku Asmaul Husna' milik mereka sendiri. Setiap halaman berisi satu nama Allah, artinya sederhana, dan gambar atau kolase yang menggambarkan maknanya. Anak dapat mewarnai, menempel stiker, atau menggambar sesuai imajinasi mereka.",
        "REFLEKSI: Guru memimpin diskusi kelompok tentang bagaimana anak dapat meneladani Asmaul Husna di rumah dan sekolah. Setiap anak berbagi pengalaman ketika mereka melihat seseorang meneladani sifat Allah, seperti ibu yang Ar-Rahman saat merawat adik yang sakit."
      ],
      penutup: "Guru mengajak anak duduk melingkar dan menggenggam tangan teman di sebelahnya. Bersama-sama, mereka menyebutkan kembali Asmaul Husna yang telah dipelajari dengan suara lembut dan penuh makna. Guru mengajak anak berdoa penutup dengan penuh rasa syukur kepada Allah atas semua nikmat yang telah diberikan. Guru memberikan tanda penghargaan berupa stiker Asmaul Husna kepada setiap anak sebagai bentuk apresiasi dan pengingat untuk selalu meneladani sifat-sifat Allah. Guru menutup dengan salam, pelukan, dan senyuman kasih sayang."
    },
    lampiran: "Lampiran 1: Kartu-kartu Asmaul Husna (Ar-Rahman, Ar-Rahim, Al-Malik, Al-Quddus, As-Salam, Al-Mu'min, Al-Muhaymin, Al-Aziz, Al-Jabbar, Al-Mutakabbir, Al-Khaliq, Al-Bari', Al-Musawwir, Al-Ghaffar, Al-Qahhar, Al-Wahhab, Ar-Razzaq, Al-Fattah, Al-Alim, Al-Qabid, Al-Basit, Al-Khafid, Ar-Rafi', Al-Mu'izz, Al-Mudhill, As-Sami', Al-Basir, Al-Hakam, Al-Adl, Al-Latif, Al-Khabir, Al-Halim, Al-Azim, Al-Ghafur, Asy-Syakur, Al-Aliyy, Al-Kabir, Al-Hafiz, Al-Muqit, Al-Hasib, Al-Jalil, Al-Karim, Ar-Raqib, Al-Mujib, Al-Wasi', Al-Hakim, Al-Wadud, Al-Majid, Al-Ba'its, As-Syahid, Al-Haqq, Al-Wakil, Al-Qawiyy, Al-Matin, Al-Waliyy, Al-Hamid, Al-Muhsi, Al-Mubdi', Al-Mu'id, Al-Muhyi, Al-Mumit, Al-Hayy, Al-Qayyum, Al-Wajid, Al-Majid, Al-Wahid, As-Samad, Al-Qadir, Al-Muqtadir, Al-Muqaddim, Al-Mu'akhkhir, Al-Awwal, Al-Akhir, Az-Zahir, Al-Batin, Al-Wali, Al-Muta'ali, Al-Barr, At-Tawwab, Al-Muntaqim, Al-Afuww, Ar-Ra'uf, Malikul Mulk, Dzul Jalali wal Ikram, Al-Muqsit, Al-Jami', Al-Ghani, Al-Mughni, Al-Mani', Ad-Darr, An-Nafi', An-Nur, Al-Hadi, Al-Badi', Al-Baqi, Al-Warith, Ar-Rasyid, As-Sabur)."
  },
  {
    tema: "Adab Makan dan Minum",
    kelompokUsia: "B",
    topikKBC: "Beriman dan Berakhlak Mulia",
    tujuanKBC: "Anak dapat memahami dan melaksanakan adab-adab makan dan minum sesuai ajaran Islam dengan penuh rasa syukur dan kebersamaan, memahami bahwa makan dan minum adalah nikmat dari Allah yang harus dijaga dengan cara yang baik dan halal, serta menjaga kebersihan dan kesehatan tubuh melalui perilaku makan yang benar.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak membaca doa sebelum dan sesudah makan dengan lancar dan penuh pemahaman, mengucapkan Alhamdulillah sebagai wujud syukur, serta menghormati orang yang memberi makan dengan ucapan terima kasih yang tulus.",
      berkebinekaan_global: "Anak menghargai berbagai jenis makanan dari berbagai budaya, memahami bahwa setiap makanan memiliki keunikan dan keindahan, serta menghormati teman yang memiliki preferensi makanan berbeda karena alasan kesehatan atau agama.",
      gotong_royong: "Anak membantu menyiapkan meja makan, berbagi makanan dengan teman, membersihkan tempat makan bersama-sama, serta memastikan semua teman mendapat porsi yang cukup.",
      mandiri_dan_kreatif: "Anak dapat makan dengan sendiri menggunakan alat makan yang tepat, menyusun makanan di piring dengan rapi, membuat bentuk makanan yang menarik, serta membersihkan diri setelah makan dengan mandiri.",
      bernalar_kritis: "Anak dapat membedakan makanan yang halal dan haram, menjelaskan mengapa kita harus menjaga kebersihan saat makan, memahami manfaat setiap jenis makanan bagi tubuh, serta membuat pilihan makanan yang sehat.",
      sehat_jasmani_dan_rohani: "Anak memilih makanan yang sehat dan bergizi, mencuci tangan sebelum dan sesudah makan, mengunyah makanan dengan baik, tidak berlebihan dalam makan, serta menjaga kebersihan tempat makan.",
      warga_negara: "Anak memahami pentingnya ketertiban saat makan bersama, menghormati hak orang lain untuk makan dengan nyaman, serta menjaga lingkungan tetap bersih dari sampah makanan."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran yang praktis dan menyenangkan, anak akan:\n1. Menghafal dan memahami doa sebelum dan sesudah makan dengan benar\n2. Mempraktikkan adab makan dan minum sesuai ajaran Islam (cuci tangan, duduk dengan tertib, makan dengan tangan kanan, dll)\n3. Menjelaskan makna dan hikmah dari setiap adab makan dan minum yang dipelajari\n4. Membedakan perilaku makan yang baik dan kurang baik dengan memberikan alasan yang tepat\n5. Menerapkan adab makan dalam kehidupan sehari-hari di rumah dan sekolah\n6. Menghargai makanan sebagai nikmat Allah dengan tidak membuang-buang makanan\n7. Menunjukkan rasa syukur melalui doa, ucapan terima kasih, dan perilaku yang menghargai makanan",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 1 hari (± 2 jam) dengan pendekatan experiential learning:\n- Pembelajaran berbasis pengalaman langsung dan praktik nyata\n- Metode modeling dan demonstration dari guru\n- Pembelajaran kolaboratif melalui kegiatan makan bersama\n- Simulasi dan role playing situasi makan yang berbeda\n- Penilaian prosesual melalui observasi langsung\n- Integrasi nilai-nilai kebersihan, kesehatan, dan kerendahan hati\n- Lingkungan belajar yang hangat dan memberikan contoh nyata",
    kegiatanPembelajaran: {
      pendahuluan: "Guru menyambut anak dengan senyuman dan ajakan cuci tangan sebelum memulai kegiatan. Guru menanyakan: 'Siapa yang suka makan? Apa yang kita lakukan sebelum makan?' Guru memutarkan video atau menampilkan gambar anak-anak yang sedang makan dengan baik dan buruk. Guru mengajak anak menganalisis perbedaan antara dua gambar tersebut dan menentukan mana yang sesuai adab Islam. Guru memperkenalkan tema hari ini dengan cerita: 'Hari ini kita akan belajar menjadi anak yang beradab saat makan dan minum, sehingga Allah senang dan kita semua sehat.'",
      inti: [
        "EKSPLORASI: Guru membagi anak menjadi beberapa kelompok kecil. Setiap kelompok mendapat kartu berbagai adab makan (cuci tangan, baca doa, duduk tertib, pakai tangan kanan, tidak berbicara mulut penuh, dll). Anak mendiskusikan dan mempraktikkan adab tersebut dengan menggunakan properti mainan makanan. Setiap kelompok mempresentasikan hasil praktik mereka.",
        "ELABORASI: Guru mendemonstrasikan cara makan yang baik secara lengkap: mulai dari cuci tangan, berdoa, duduk dengan posisi yang baik, menggunakan tangan kanan, mengunyah dengan tertib, hingga berdoa sesudah makan. Anak diminta menirukan dan praktik dengan makanan sebenarnya (snack yang disiapkan). Guru memberikan umpan balik yang konstruktif dan penguatan positif.",
        "KONFIRMASI: Guru mengajak anak menyusun 'Puzzle Adab Makan' berbagai urutan langkah-langkah makan yang baik. Anak berdiskusi dan menempatkan setiap langkah pada urutan yang benar. Guru mengajak anak menyanyikan lagu tentang adab makan dengan gerakan yang menyenangkan.",
        "PRAKTIK: Anak berpartisipasi dalam 'Pesta Makan Bersama' di mana setiap anak mempraktikkan semua adab yang telah dipelajari. Guru berkeliling mengamati dan mencatat perilaku anak. Setelah makan, anak membersihkan tempat makan mereka dengan bantuan guru.",
        "REFLEKSI: Guru mengajak anak duduk melingkar dan berbagi pengalaman: 'Bagaimana perasaanmu ketika makan dengan adab yang baik? Apa yang kamu rasakan berbeda dengan kebiasaanmu sebelumnya?' Anak mengungkapkan pikiran dan perasaan mereka secara bebas."
      ],
      penutup: "Guru mengajak anak mengevaluasi diri sendiri dengan menunjuk jempol ke atas (sudah sangat baik), menyamping (perlu ditingkatkan), atau ke bawah (perlu banyak belajar) untuk setiap adab makan yang telah dipelajari. Guru memimpin doa penutup dengan memohon kepada Allah agar selalu diberikan kemampuan untuk menjaga adab makan dalam setiap kesempatan. Guru memberikan 'Sertifikat Adab Makan' kecil kepada setiap anak sebagai pengingat dan apresiasi. Guru menutup dengan salam dan ucapan terima kasih atas partisipasi aktif setiap anak."
    },
    lampiran: "Lampiran 1: Kartu-kartu adab makan dengan gambar ilustrasi. Lampiran 2: Lirik lagu adab makan. Lampiran 3: Doa sebelum dan sesudah makan. Lampiran 4: Puzzle urutan langkah makan yang baik. Lampiran 5: Sertifikat Adab Makan. Lampiran 6: Rubrik penilaian observasi praktik makan."
  },
  {
    tema: "Mengenal Malaikat Allah",
    kelompokUsia: "B",
    topikKBC: "Beriman dan Berakhlak Mulia",
    tujuanKBC: "Anak dapat mengenal dan memahami keberadaan malaikat sebagai makhluk Allah yang tidak terlihat, memahami tugas-tugas utama beberapa malaikat, menumbuhkan rasa kagum dan keimanan kepada Allah atas ciptaan-Nya yang luar biasa, serta memahami bahwa malaikat selalu mendampingi dan mencatat amal kebaikan kita.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak percaya kepada keberadaan malaikat sebagai makhluk Allah, mengenal nama dan tugas 10 malaikat utama (Jibril menyampaikan wahyu, Mikail mengatur rezeki, Israfil meniup sangkakala, Izrail mencabut nyawa, Munkar dan Nakir menanyakan di kubur, Raqib dan Atid mencatat amal, Malik penjaga neraka, Ridwan penjaga surga), serta mengimani bahwa malaikat selalu menjaga kita.",
      berkebinekaan_global: "Anak memahami bahwa keyakinan kepada malaikat adalah bagian dari ajaran Islam sambil menghargai teman-teman yang memiliki kepercayaan berbeda, serta belajar bersikap toleran dan menghormati perbedaan keyakinan.",
      gotong_royong: "Anak belajar dari teladan malaikat yang saling bekerja sama untuk menjalankan tugas Allah, membantu teman yang kesulitan memahami pelajaran, serta bekerja sama dalam kelompok untuk membuat karya tentang malaikat.",
      mandiri_dan_kreatif: "Anak dapat menceritakan kembali tugas malaikat dengan bahasa sendiri, membuat karya seni atau buku cerita tentang malaikat, menemukan contoh perilaku yang mencerminkan iman kepada malaikat dalam kehidupan sehari-hari, serta mempresentasikannya dengan percaya diri.",
      bernalar_kritis: "Anak dapat menjelaskan mengapa kita tidak bisa melihat malaikat, memahami perbedaan antara malaikat dan manusia, menganalisis mengapa Allah menciptakan malaikat, serta mengajukan pertanyaan-pertanyaan yang relevan tentang malaikat.",
      sehat_jasmani_dan_rohani: "Anak menjaga kebersihan hati dengan selalu berbuat baik karena tahu malaikat mencatat amal kita, melakukan gerakan fisik yang melambangkan tugas malaikat, serta menjaga kesehatan sebagai bentuk rasa syukur kepada Allah.",
      warga_negara: "Anak memahami dirinya sebagai makhluk ciptaan Allah yang diperhatikan dan dijaga, menghargai keberadaan semua makhluk Allah, serta bersikap baik kepada semua karena tahu bahwa malaikat selalu mengawasi dan mencatat perbuatan kita."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran yang menarik dan penuh imajinasi, anak akan:\n1. Menyebutkan minimal 10 nama malaikat dan tugas-tugasnya dengan benar\n2. Memahami bahwa malaikat adalah makhluk Allah yang tidak terlihat dan selalu taat\n3. Menjelaskan perbedaan antara malaikat dan manusia dengan bahasa sederhana\n4. Menghubungkan iman kepada malaikat dengan perilaku sehari-hari\n5. Menceritakan kembali informasi tentang malaikat dengan cara yang kreatif\n6. Menunjukkan rasa kagum dan syukur kepada Allah atas penciptaan malaikat\n7. Mempraktikkan perilaku yang mencerminkan iman kepada malaikat (berbuat baik, jujur, dll)",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 1 hari (± 2 jam) dengan pendekatan storytelling dan imaginative learning:\n- Pembelajaran berbasis cerita dan narasi yang menarik\n- Metode inkuiri melalui pertanyaan pemicu\n- Pembelajaran kolaboratif melalui proyek kelompok\n- Penggunaan media visual dan audio untuk memperkuat pemahaman\n- Penilaian berbasis kinerja dan produk karya\n- Integrasi nilai-nilai iman, taqwa, dan akhlak mulia\n- Lingkungan belajar yang hangat, penuh keajaiban, dan menginspirasi",
    kegiatanPembelajaran: {
      pendahuluan: "Guru membuka dengan salam, senyuman, dan pelukan hangat kepada setiap anak. Guru memutarkan audio suara langit atau musik yang lembut dan menenangkan. Guru bertanya dengan suara lembut: 'Anak-anak, pernahkah kamu merasa seperti ada seseorang yang mengawasi dan menjagamu meskipun kamu tidak melihatnya? Ada makhluk Allah yang luar biasa yang selalu bersama kita, mencatat semua kebaikan yang kita lakukan. Siapa ya kira-kira?' Guru menampilkan gambar-gambar yang menunjukkan keindahan ciptaan Allah dan memunculkan rasa ingin tahu tentang malaikat.",
      inti: [
        "EKSPLORASI: Guru membagikan kartu-kartu malaikat (Jibril, Mikail, Israfil, Izrail, Munkar, Nakir, Raqib, Atid, Malik, Ridwan) kepada anak-anak secara berpasangan. Setiap pasangan mendiskusikan dan mencari tahu tugas malaikat tersebut dengan bantuan buku cerita yang disediakan. Guru berkeliling memfasilitasi diskusi dan menjawab pertanyaan anak.",
        "ELABORASI: Guru menceritakan kisah-kisah tentang malaikat dengan cara yang menarik dan penuh emosi. Misalnya: cerita tentang Jibril yang turun ke Gua Hira untuk memberikan wahyu pertama kepada Nabi Muhammad SAW, cerita tentang Raqib dan Atid yang mencatat amal baik kita setiap hari. Guru menggunakan boneka tangan atau puppet untuk memerankan kisah tersebut.",
        "KONFIRMASI: Guru mengajak anak bermain 'Guess the Angel' di mana guru memberikan clue tentang tugas malaikat dan anak menebak namanya. Setiap anak yang benar mendapat poin. Guru mengajak anak menyanyikan lagu tentang malaikat dengan gerakan tangan yang menggambarkan tugas-tugas mereka.",
        "PRAKTIK: Anak membuat 'Buku Malaikat' milik mereka sendiri. Setiap halaman berisi nama malaikat, tugasnya, dan gambar yang menggambarkan tugas tersebut. Anak dapat mewarnai, menempel stiker bintang, atau menggambar malaikat dengan imajinasi mereka. Guru berkeliling memberikan apresiasi dan bimbingan.",
        "REFLEKSI: Guru mengajak anak duduk melingkar dan memimpin diskusi: 'Setelah mengetahui tentang malaikat, bagaimana perasaanmu? Apa yang akan kamu lakukan berbeda mulai hari ini?' Anak berbagi refleksi dan komitmen untuk berbuat lebih banyak kebaikan."
      ],
      penutup: "Guru mengajak anak menutup mata dan membayangkan malaikat yang selalu ada di samping kita, mencatat setiap kebaikan yang kita lakukan. Guru memimpin doa dengan penuh rasa syukur dan kekaguman kepada Allah yang telah menciptakan malaikat sebagai penjaga dan pencatat amal kita. Guru memberikan 'Bintang Malaikat' kepada setiap anak sebagai pengingat untuk selalu berbuat baik. Guru menutup dengan salam, senyuman, dan ucapan: 'Terima kasih anak-anak, hari ini malaikat pasti sangat senang mencatat banyak kebaikan kalian.'"
    },
    lampiran: "Lampiran 1: Kartu-kartu nama dan tugas malaikat. Lampiran 2: Buku cerita tentang malaikat. Lampiran 3: Lirik lagu malaikat. Lampiran 4: Template 'Buku Malaikat'. Lampiran 5: Bintang stiker penghargaan. Lampiran 6: Rubrik penilaian partisipasi dan karya anak."
  },
  // Pilar 2: Berkebinekaan Global (3 templates)
  {
    tema: "Budaya Indonesia: Batik, Wayang, dan Rumah Adat",
    kelompokUsia: "B",
    topikKBC: "Berkebinekaan Global",
    tujuanKBC: "Anak dapat mengenal, menghargai, dan bangga dengan keberagaman budaya Indonesia melalui batik, wayang, dan rumah adat, memahami bahwa setiap daerah memiliki keunikan dan keindahan yang berbeda-beda, serta menumbuhkan rasa cinta dan bangga terhadap tanah air sebagai bagian dari identitas mereka.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak bersyukur kepada Allah atas keberagaman budaya yang ada di Indonesia, menghargai ciptaan seni manusia sebagai anugerah Allah, serta menghormati perbedaan budaya sebagai bentuk kasih sayang kepada sesama.",
      berkebinekaan_global: "Anak mengenal minimal 5 motif batik dari berbagai daerah (Batik Jawa, Batik Bali, Batik Sumatera, dll), mengenal jenis-jenis wayang (Wayang Kulit, Wayang Golek, Wayang Orang), serta mengenal minimal 5 rumah adat (Rumah Gadang, Tongkonan, Joglo, Kebaya, Honai).",
      gotong_royong: "Anak bekerja sama dalam kelompok untuk membuat karya seni batik sederhana, membantu teman yang kesulitan dalam proyek seni, serta mempresentasikan hasil karya kelompok dengan bangga.",
      mandiri_dan_kreatif: "Anak membuat motif batik sederhana dengan teknik kolase atau crayon resist, membuat wayang kertas dan menyiapkan pertunjukan wayang mini, membuat rumah adat dari bahan daur ulang, serta mempresentasikan karya dengan percaya diri.",
      bernalar_kritis: "Anak membedakan berbagai motif batik dan asal daerahnya, menganalisis fungsi wayang sebagai media pendidikan dan hiburan, membandingkan berbagai rumah adat dan memahami kenapa bentuknya berbeda, serta mengajukan pertanyaan tentang budaya Indonesia.",
      sehat_jasmani_dan_rohani: "Anak melakukan gerakan-gerakan tangan dan tubuh saat membuat karya seni, menjaga kebersihan saat bekerja dengan pewarna, serta menikmati proses berkarya dengan penuh ketenangan dan kebahagiaan.",
      warga_negara: "Anak mengidentifikasi diri sebagai bagian dari bangsa Indonesia yang kaya budaya, bangga dengan keberagaman budaya Indonesia, serta menyadari tanggung jawab untuk melestarikan budaya bangsa."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran yang kaya budaya dan kreatif, anak akan:\n1. Mengenal minimal 5 motif batik dari berbagai daerah Indonesia\n2. Memahami makna dan filosofi dari setiap motif batik yang dipelajari\n3. Mengenal jenis-jenis wayang dan fungsinya dalam budaya Indonesia\n4. Mengenal minimal 5 rumah adat dari berbagai daerah\n5. Memahami keunikan dan fungsi setiap rumah adat\n6. Membuat karya seni sederhana yang terinspirasi dari budaya Indonesia\n7. Menunjukkan rasa bangga dan cinta terhadap budaya Indonesia",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 2 hari (± 4 jam total) dengan pendekatan project-based learning:\n- Pembelajaran berbasis proyek seni dan budaya\n- Metode eksplorasi langsung dengan benda asli atau replika\n- Pembelajaran kolaboratif melalui kerja kelompok\n- Pembelajaran lintas mata pelajaran (seni, bahasa, sosial)\n- Penilaian berbasis produk dan proses\n- Integrasi nilai-nilai cinta tanah air dan toleransi\n- Lingkungan belajar yang kaya visual dan inspiratif",
    kegiatanPembelajaran: {
      pendahuluan: "Guru memulai dengan memutarkan lagu 'Indonesia Pusaka' atau lagu daerah sambil menampilkan gambar-gambar keindahan Indonesia. Guru bertanya: 'Anak-anak, tahu tidak Indonesia punya banyak sekali keunikan? Setiap daerah punya ciri khas yang berbeda-beda. Siapa yang pernah melihat batik? Wayang? Rumah adat?' Guru menampilkan berbagai contoh batik, wayang, dan rumah adat dan mengajak anak mengamati perbedaan-perbedaannya. Guru memperkenalkan tema: 'Hari ini dan besok kita akan menjadi penjelajah budaya Indonesia!'",
      inti: [
        "EKSPLORASI BATIK: Guru menampilkan kain batik asli atau replika dari berbagai daerah (Batik Solo, Batik Pekalongan, Batik Bali, Batik Palembang). Anak diajak mengamati motif, warna, dan pola dengan kaca pembesar. Setiap anak memilih motif batik favorit dan menjelaskan alasannya. Guru menjelaskan makna dan filosofi di balik setiap motif.",
        "PRAKTIK BATIK: Anak membuat 'Batik Kertas' dengan teknik crayon resist. Anak menggambar motif batik dengan crayon, kemudian mewarnai dengan cat air sehingga motif crayon tahan terhadap warna. Setiap anak membuat karya batik unik mereka sendiri.",
        "EKSPLORASI WAYANG: Guru menampilkan berbagai jenis wayang (Wayang Kulit, Wayang Golek, Wayang Kertas). Guru menceritakan kisah singkat tentang wayang dan fungsinya. Anak diajak memegang dan mengamati wayang dari dekat. Guru menjelaskan karakter tokoh-tokoh wayang seperti Arjuna, Srikandi, dan Gatotkaca.",
        "PRAKTIK WAYANG: Anak membuat wayang kertas mereka sendiri. Anak menggambar tokoh wayang, mewarnainya, dan memasang tangkai dari bambu sederhana. Setiap anak mempresentasikan wayang yang mereka buat dan menceritakan karakternya.",
        "EKSPLORASI RUMAH ADAT: Guru menampilkan gambar atau model rumah adat (Rumah Gadang Sumatera Barat, Tongkonan Sulawesi Selatan, Joglo Jawa, Rumah Kebaya Kalimantan, Honai Papua). Guru menjelaskan bentuk, fungsi, dan keunikan setiap rumah adat. Anak berdiskusi tentang mengapa setiap daerah punya rumah yang berbeda.",
        "PRAKTIK RUMAH ADAT: Anak bekerja dalam kelompok untuk membuat rumah adat dari bahan daur ulang (kotak kardus, stik es krim, kertas warna). Setiap kelompok membuat satu rumah adat dan mempresentasikan hasil karya mereka di depan kelas."
      ],
      penutup: "Guru mengajak anak memamerkan semua karya mereka (batik, wayang, rumah adat) dalam 'Pameran Budaya Indonesia' mini. Setiap anak menjelaskan karya mereka kepada teman-teman. Guru memimpin diskusi refleksi: 'Apa yang paling kamu sukai dari budaya Indonesia? Mengapa kita harus bangga dengan budaya kita?' Guru memberikan apresiasi berupa 'Sertifikat Penjelajah Budaya' kepada setiap anak. Guru memimpin doa syukur untuk Indonesia dan menutup dengan lagu kebangsaan atau lagu daerah bersama-sama."
    },
    lampiran: "Lampiran 1: Gambar-gambar batik dari berbagai daerah. Lampiran 2: Gambar-gambar wayang. Lampiran 3: Gambar-gambar rumah adat. Lampiran 4: Template wayang kertas. Lampiran 5: Bahan-bahan untuk membuat rumah adat. Lampiran 6: Lirik lagu-lagu daerah. Lampiran 7: Sertifikat Penjelajah Budaya. Lampiran 8: Rubrik penilaian proyek dan karya seni."
  },
  {
    tema: "Makanan Nusantara: Rasa dan Cerita",
    kelompokUsia: "B",
    topikKBC: "Berkebinekaan Global",
    tujuanKBC: "Anak dapat mengenal berbagai makanan khas dari berbagai daerah di Indonesia, memahami bahwa setiap daerah memiliki cita rasa dan bahan yang berbeda-beda karena kondisi geografis dan budaya, menumbuhkan rasa bangga terhadap kekayaan kuliner Indonesia, serta menghargai perbedaan selera dan budaya makan di Indonesia.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak bersyukur kepada Allah atas keberagaman rezeki berupa makanan di Indonesia, menghargai usaha petani dan pebisnis kuliner, serta berbagi makanan dengan teman sebagai bentuk kasih sayang.",
      berkebinekaan_global: "Anak mengenal minimal 10 makanan khas dari berbagai provinsi (Rendang Sumatera Barat, Sate Madura, Gudeg Yogyakarta, Pempek Palembang, Soto Lamongan, Bakso Malang, Coto Makassar, Bika Ambon Manado, Kerak Telor Jakarta, Es Teler Jawa), serta memahami bahan utama dan cara pembuatannya secara sederhana.",
      gotong_royong: "Anak bekerja sama dalam kelompok untuk membuat resep sederhana, berbagi bahan dan alat, membantu teman yang kesulitan, serta membersihkan bersama setelah kegiatan memasak.",
      mandiri_dan_kreatif: "Anak dapat menggambarkan makanan khas yang mereka suka, membuat 'Buku Resep' dengan gambar dan tulisan sederhana, menciptakan varian rasa baru dengan imajinasi, serta mempresentasikan dengan percaya diri.",
      bernalar_kritis: "Anak membedakan berbagai rasa (manis, asin, pedas, asam) dari makanan Nusantara, memahami mengapa setiap daerah punya makanan berbeda (iklim, bahan lokal, budaya), menjelaskan manfaat setiap bahan makanan bagi tubuh, serta mengajukan pertanyaan tentang makanan daerah lain.",
      sehat_jasmani_dan_rohani: "Anak memilih makanan yang sehat dari berbagai daerah, mencoba makanan baru dengan rasa ingin tahu, menjaga kebersihan saat menyiapkan dan menyantap makanan, serta menghargai makanan dengan tidak membuang-buang.",
      warga_negara: "Anak mengidentifikasi diri sebagai bagian dari bangsa Indonesia yang kaya kuliner, bangga dengan keanekaragaman makanan Indonesia, serta menyadari pentingnya melestarikan resep tradisional."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran yang lezat dan edukatif, anak akan:\n1. Mengenal minimal 10 makanan khas dari berbagai daerah di Indonesia\n2. Memahami bahan utama dan cara pembuatan sederhana setiap makanan\n3. Membedakan berbagai rasa dari makanan Nusantara\n4. Menjelaskan hubungan antara makanan dengan budaya dan geografi daerah\n5. Mempraktikkan pembuatan makanan sederhana dari resep daerah\n6. Menunjukkan rasa bangga terhadap kuliner Indonesia\n7. Menghargai perbedaan selera dan budaya makan",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 2 hari (± 4 jam total) dengan pendekatan hands-on learning:\n- Pembelajaran berbasis pengalaman langsung mencicipi dan membuat makanan\n- Metode eksperimen sensorik (mencicipi, mencium, melihat)\n- Pembelajaran kolaboratif melalui kegiatan memasak bersama\n- Pembelajaran lintas mata pelajaran (biologi, geografi, matematika ukuran)\n- Penilaian berbasis proses dan hasil\n- Integrasi nilai-nilai kebersihan, kesehatan, dan gotong royong\n- Lingkungan belajar yang hangat, aman, dan menyenangkan",
    kegiatanPembelajaran: {
      pendahuluan: "Guru menarik perhatian anak dengan aroma makanan yang lezat yang disiapkan sebelumnya. Guru bertanya: 'Wah, aromanya enak sekali! Siapa yang bisa menebak makanan apa ini? Dari daerah mana ya?' Guru menampilkan peta Indonesia dengan gambar-gambar makanan di setiap provinsi. Guru mengatakan: 'Indonesia punya ribuan makanan lezat! Setiap daerah punya makanan khas yang unik. Hari ini kita akan menjadi penjelajah rasa Nusantara!'",
      inti: [
        "EKSPLORASI RASA: Guru menyajikan sampel makanan khas dari berbagai daerah (Rendang, Sate, Gudeg, Pempek, dll dalam porsi kecil). Anak diajak mencicipi setiap makanan dan menggambarkan rasanya (manis, asin, pedas, gurih, asam). Guru mencatat respon anak di papan tulis dalam bentuk tabel.",
        "STUDI KASUS: Guru membagikan kartu berisi gambar makanan khas dan cerita singkat tentang asal-usulnya. Anak berdiskusi dalam kelompok: Mengapa makanan ini terkenal di daerah tersebut? Bahan apa yang tersedia di daerah itu? Setiap kelompok mempresentasikan temuan mereka.",
        "PRAKTIK MEMASAK: Anak berpartisipasi dalam 'Kelas Memasak Mini' untuk membuat salah satu makanan sederhana, misalnya Es Teler atau Kerupuk. Guru mendemonstrasikan langkah-langkahnya, kemudian anak mempraktikkan dengan bimbingan. Anak belajar mengukur bahan, mencampur, dan menyajikan.",
        "KREASI RESIP: Anak membuat 'Buku Resep Mini' mereka sendiri. Setiap halaman berisi gambar makanan khas yang mereka suka, daftar bahan sederhana, dan langkah-langkah membuat dengan gambar ilustrasi. Anak dapat menulis kata-kata sederhana atau mendiktekan kepada guru.",
        "PAMERAN MAKANAN: Anak memamerkan karya mereka (Buku Resep, makanan yang dibuat) dalam 'Pameran Kuliner Nusantara'. Setiap anak menjelaskan karya mereka kepada teman-teman dan guru. Anak juga membawa makanan khas dari rumah (jika memungkinkan) untuk dibagikan dan diceritakan asal-usulnya."
      ],
      penutup: "Guru mengajak anak duduk melingkar dan memimpin diskusi refleksi: 'Makanan mana yang paling kamu sukai? Apa yang kamu pelajari dari kegiatan hari ini? Mengapa kita harus bangga dengan makanan Indonesia?' Anak berbagi pengalaman dan perasaan mereka. Guru memberikan 'Sertifikat Juru Masak Cilik' atau 'Bintang Kuliner' kepada setiap anak. Guru memimpin doa syukur atas rezeki makanan yang berlimpah dan menutup dengan ajakan untuk selalu menghargai makanan dan tidak membuang-buangnya."
    },
    lampiran: "Lampiran 1: Peta Indonesia dengan gambar makanan khas. Lampiran 2: Kartu-kartu informasi makanan khas. Lampiran 3: Resep-resep sederhana untuk anak. Lampiran 4: Template Buku Resep Mini. Lampiran 5: Tabel sensorik rasa. Lampiran 6: Sertifikat Juru Masak Cilik. Lampiran 7: Rubrik penilaian partisipasi dan karya."
  },
  {
    tema: "Pakaian Adat Nusantara",
    kelompokUsia: "B",
    topikKBC: "Berkebinekaan Global",
    tujuanKBC: "Anak dapat mengenal berbagai pakaian adat dari berbagai provinsi di Indonesia, memahami bahwa setiap daerah memiliki ciri khas pakaian yang berbeda-beda karena budaya, iklim, dan sejarah yang berbeda, menumbuhkan rasa bangga terhadap kekayaan budaya Indonesia, serta menghargai perbedaan dalam berpakaian sebagai bentuk keragaman.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak bersyukur kepada Allah atas keberagaman budaya berpakaian, menghargai ciptaan seni dalam pakaian adat sebagai anugerah Allah, serta menghormati perbedaan pakaian orang lain sebagai bentuk kasih sayang.",
      berkebinekaan_global: "Anak mengenal minimal 10 pakaian adat dari berbagai provinsi (Kebaya Jawa, Ulos Batak, Baju Kurung Sumatera, Baju Bodo Sulawesi Selatan, Pakaian Adat Bali, Pakaian Adat Papua, Pakaian Adat Dayak Kalimantan, Pakaian Adat Sumba, Pakaian Adat Timor, Pakaian Adat Maluku), serta memahami ciri khas dan maknanya.",
      gotong_royong: "Anak bekerja sama dalam kelompok untuk membuat pakaian adat dari kertas, membantu teman mengenakan pakaian adat, serta mempresentasikan hasil karya kelompok dengan bangga.",
      mandiri_dan_kreatif: "Anak membuat pakaian adat kertas dengan teknik origami atau kolase, menghias pakaian dengan motif khas daerah, mempresentasikan karya dengan percaya diri, serta menceritakan makna pakaian adat yang dibuat.",
      bernalar_kritis: "Anak membedakan berbagai pakaian adat dan asal daerahnya, menganalisis mengapa pakaian adat berbeda-beda (iklim, bahan, budaya), membandingkan pakaian adat dengan pakaian sehari-hari, serta mengajukan pertanyaan tentang pakaian daerah lain.",
      sehat_jasmani_dan_rohani: "Anak bergerak dan menari dengan pakaian adat kertas, menjaga kebersihan saat bekerja dengan kertas dan pewarna, serta menikmati proses berkarya dengan penuh kebahagiaan.",
      warga_negara: "Anak mengidentifikasi diri sebagai bagian dari bangsa Indonesia yang kaya budaya, bangga dengan keanekaragaman pakaian adat, serta menyadari pentingnya melestarikan budaya berpakaian tradisional."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran yang kreatif dan budaya, anak akan:\n1. Mengenal minimal 10 pakaian adat dari berbagai daerah di Indonesia\n2. Memahami ciri khas dan makna dari setiap pakaian adat yang dipelajari\n3. Menjelaskan hubungan antara pakaian adat dengan budaya dan lingkungan daerah\n4. Membuat karya pakaian adat sederhana dari kertas\n5. Menunjukkan rasa bangga terhadap kekayaan budaya Indonesia\n6. Menghargai perbedaan dalam berpakaian sebagai bentuk keragaman\n7. Mempraktikkan sikap toleran terhadap perbedaan budaya berpakaian",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 2 hari (± 4 jam total) dengan pendekatan arts-based learning:\n- Pembelajaran berbasis seni dan kerajinan tangan\n- Metode eksplorasi visual dengan gambar dan video\n- Pembelajaran kolaboratif melalui proyek kelompok\n- Pembelajaran lintas mata pelajaran (seni, budaya, bahasa)\n- Penilaian berbasis produk kreatif\n- Integrasi nilai-nilai toleransi, bangga budaya, dan kreativitas\n- Lingkungan belajar yang kaya warna dan inspiratif",
    kegiatanPembelajaran: {
      pendahuluan: "Guru memulai dengan menampilkan video tari tradisional dengan berbagai pakaian adat atau menunjukkan gambar-gambar pakaian adat yang indah. Guru bertanya: 'Wah, pakaian-pakaian ini cantik sekali! Ada yang tahu ini pakaian dari daerah mana? Kenapa bentuknya berbeda-beda?' Guru menampilkan peta Indonesia dan menunjukkan berbagai pakaian adat di setiap daerah. Guru mengatakan: 'Indonesia punya ratusan pakaian adat yang cantik! Hari ini kita akan belajar dan membuat pakaian adat kita sendiri!'",
      inti: [
        "EKSPLORASI VISUAL: Guru menampilkan gambar-gambar pakaian adat dari berbagai daerah (Kebaya, Ulos, Baju Bodo, dll) dalam ukuran besar. Anak diajak mengamati detail, warna, motif, dan bentuk. Guru menjelaskan asal daerah, ciri khas, dan makna setiap pakaian adat. Anak diminta memilih pakaian adat favorit mereka dan menjelaskan alasannya.",
        "VIDEO DAN CERITA: Guru memutar video singkat tentang pakaian adat atau menceritakan kisah di balik pakaian adat tertentu. Misalnya, cerita tentang Kebaya yang dikenakan oleh perempuan Jawa sebagai simbol kesopanan dan keanggunan, atau Ulos Batak yang memiliki makna perlindungan dan kasih sayang.",
        "PRAKTIK KREATIF: Anak membuat 'Pakaian Adat Kertas' mereka sendiri. Guru menyediakan template pakaian adat sederhana yang dapat dicetak. Anak memotong, menghias dengan kertas warna, menambahkan motif khas daerah, dan membuat pakaian adat yang unik. Anak dapat memilih pakaian adat mana yang ingin mereka buat.",
        "PERMAINAN PERAN: Anak memakai pakaian adat kertas yang mereka buat dan bermain peran sebagai 'Duta Budaya' dari daerah tersebut. Setiap anak memperkenalkan diri: 'Halo, saya dari [daerah]. Pakaian ini disebut [nama pakaian]. Ciri khasnya adalah [detail]. Maknanya adalah [makna].' Anak lain bertanya tentang pakaian adat tersebut.",
        "PAMERAN FASHION: Guru mengadakan 'Peragaan Busana Adat' mini di mana setiap anak memperagakan pakaian adat kertas mereka dengan jalan di depan kelas sambil guru atau teman menjelaskan tentang pakaian tersebut. Musik tradisional diputar sebagai latar belakang."
      ],
      penutup: "Guru mengajak anak berkumpul dan memimpin diskusi refleksi: 'Pakaian adat mana yang paling kamu sukai? Apa yang kamu pelajari hari ini? Mengapa kita harus bangga dengan pakaian adat Indonesia?' Anak berbagi refleksi. Guru menampilkan semua karya anak di dinding kelas sebagai 'Galeri Pakaian Adat Nusantara'. Guru memberikan 'Sertifikat Desainer Cilik' atau 'Bintang Budaya' kepada setiap anak. Guru memimpin doa syukur atas kekayaan budaya Indonesia dan menutup dengan ajakan untuk selalu bangga dengan budaya bangsa sendiri."
    },
    lampiran: "Lampiran 1: Gambar-gambar pakaian adat dari berbagai daerah. Lampiran 2: Video pakaian adat dan tarian tradisional. Lampiran 3: Template pakaian adat kertas. Lampiran 4: Kertas warna, gunting, lem, dan bahan hias. Lampiran 5: Musik tradisional Indonesia. Lampiran 6: Sertifikat Desainer Cilik. Lampiran 7: Rubrik penilaian kreatifitas dan presentasi."
  },
  // Pilar 3: Gotong Royong (3 templates)
  {
    tema: "Bekerja Sama Membuat Taman Sekolah",
    kelompokUsia: "B",
    topikKBC: "Gotong Royong",
    tujuanKBC: "Anak dapat memahami pentingnya kerja sama dan gotong royong dalam mewujudkan lingkungan yang indah dan sehat, melaksanakan kegiatan berkebun secara kolaboratif, memahami tanggung jawab bersama terhadap lingkungan, serta menumbuhkan rasa cinta dan peduli terhadap alam dan lingkungan sekitar.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak bersyukur kepada Allah atas ciptaan-Nya berupa tumbuhan dan alam, merawat tanaman sebagai bentuk kasih sayang kepada ciptaan Allah, serta memahami bahwa menjaga alam adalah amanah dari Allah.",
      berkebinekaan_global: "Anak memahami bahwa setiap negara memiliki taman dan kebun yang berbeda-beda, menghargai berbagai jenis tanaman dari berbagai daerah, serta menghormati teman yang memiliki preferensi tanaman berbeda.",
      gotong_royong: "Anak bekerja sama dalam kelompok untuk membuat taman sekolah, membagi tugas secara adil (menggali, menanam, menyiram, membersihkan), membantu teman yang kesulitan, serta saling mengingatkan untuk merawat tanaman.",
      mandiri_dan_kreatif: "Anak dapat menanam benih dengan benar, merancang taman mini di pot, membuat tanda tanaman kreatif, serta merawat tanaman dengan mandiri (menyiram, membersihkan daun kering).",
      bernalar_kritis: "Anak membedakan berbagai jenis tanaman dan cara merawatnya, memahami siklus hidup tanaman (benih → tunas → tumbuhan dewasa), menjelaskan mengapa tanaman membutuhkan air, matahari, dan tanah, serta mengajukan pertanyaan tentang pertumbuhan tanaman.",
      sehat_jasmani_dan_rohani: "Anak bergerak aktif saat berkebun (menggali, menanam, menyiram), menyentuh tanah dan tanaman sebagai terapi alami, bernapas udara segar di taman, serta menikmati keindahan alam dengan ketenangan.",
      warga_negara: "Anak memahami dirinya sebagai bagian dari komunitas sekolah yang bertanggung jawab atas lingkungan, sadar bahwa taman adalah milik bersama yang harus dijaga, serta berpartisipasi dalam kegiatan lingkungan sekolah."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran berbasis proyek lingkungan, anak akan:\n1. Memahami konsep gotong royong dan kerja sama dalam keberlanjutan lingkungan\n2. Menjelaskan tahapan menanam dan merawat tanaman dengan benar\n3. Mempraktikkan kegiatan berkebun secara kolaboratif\n4. Memahami siklus hidup tanaman dan kebutuhannya\n5. Menunjukkan tanggung jawab terhadap lingkungan sekolah\n6. Menumbuhkan rasa cinta dan peduli terhadap alam\n7. Mempraktikkan nilai-nilai gotong royong dalam kegiatan sehari-hari",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 2-3 hari (± 6 jam total) dengan pendekatan project-based learning:\n- Pembelajaran berbasis proyek lingkungan nyata\n- Metode experiential learning di luar ruangan\n- Pembelajaran kolaboratif melalui kerja kelompok\n- Pembelajaran lintas mata pelajaran (IPA, matematika, seni, PKn)\n- Penilaian berbasis proses dan hasil jangka panjang\n- Integrasi nilai-nilai kepedulian lingkungan dan tanggung jawab\n- Lingkungan belajar di alam terbuka yang menyenangkan",
    kegiatanPembelajaran: {
      pendahuluan: "Guru membawa anak ke area luar ruangan sekolah yang akan dijadikan taman. Guru bertanya: 'Anak-anak, apa yang kalian lihat di sini? Bagaimana perasaan kalian melihat tempat ini? Apakah tempat ini bisa menjadi lebih indah?' Guru menampilkan gambar-gambar taman yang indah dan menarik. Guru mengatakan: 'Jika kita bekerja sama, kita bisa membuat tempat ini menjadi taman yang indah dan sehat! Siapa yang mau membantu?' Guru memperkenalkan proyek 'Taman Sekolah Kita' dan membagi anak menjadi beberapa kelompok dengan tugas berbeda.",
      inti: [
        "PERENCANAAN: Setiap kelompok mendiskusikan dan merencanakan bagian taman yang akan mereka kerjakan. Kelompok A bertugas membuat area bunga, Kelompok B membuat area sayuran, Kelompok C membuat area tanaman hias. Guru memfasilitasi diskusi dan membantu anak membuat sketsa sederhana taman mereka.",
        "PERSIAPAN: Guru dan anak bersama-sama menyiapkan alat dan bahan (cangkul, sekop, pot, tanah, benih, pupuk). Guru menjelaskan fungsi setiap alat dan cara menggunakannya dengan aman. Anak membagi tugas: ada yang mengambil tanah, ada yang menyiapkan benih, ada yang menyiapkan pot.",
        "PRAKTIK MENANAM: Guru mendemonstrasikan cara menanam benih dengan benar: mengisi pot dengan tanah, membuat lubang kecil, memasukkan benih, menutup dengan tanah, dan menyiram. Anak mempraktikkan dengan bimbingan. Setiap anak menanam minimal 2-3 benih. Guru berkeliling memberikan bimbingan dan penguatan.",
        "PEMAKAMAN TANDA: Anak membuat tanda tanaman kreatif dari tongkat es krim dan kertas. Setiap tanda berisi nama tanaman, tanggal ditanam, dan nama anak yang merawatnya. Anak menghias tanda dengan gambar dan warna yang cerah.",
        "PELAKSANAAN GOTONG ROYONG: Setiap kelompok menata tanaman mereka di area yang ditentukan. Anak bekerja sama mengangkat pot, menyusun tanaman, dan membersihkan area sekitar. Guru mengamati dan mencatat contoh perilaku gotong royong yang ditunjukkan anak.",
        "PERAWATAN RUTIN: Guru menjelaskan bahwa tanaman membutuhkan perawatan rutin. Anak membuat jadwal penyiraman dan perawatan secara bergantian. Setiap anak memiliki tanggung jawab untuk merawat tanaman tertentu."
      ],
      penutup: "Guru mengajak anak berkumpul di taman yang baru dibuat. Guru memimpin refleksi: 'Lihat! Taman ini menjadi indah karena kita bekerja sama. Apa yang kamu rasakan saat melihat hasil kerja keras kita? Apa yang kamu pelajari tentang gotong royong?' Anak berbagi pengalaman dan perasaan mereka. Guru memberikan 'Sertifikat Pejuang Lingkungan' atau 'Bintang Taman' kepada setiap anak. Guru memimpin doa syukur atas keindahan ciptaan Allah dan menutup dengan ajakan untuk terus merawat taman bersama-sama sebagai tanggung jawab kolektif."
    },
    lampiran: "Lampiran 1: Gambar-gambar taman yang indah. Lampiran 2: Sketsa area taman sekolah. Lampiran 3: Daftar alat dan bahan berkebun. Lampiran 4: Jadwal penyiraman dan perawatan. Lampiran 5: Template tanda tanaman. Lampiran 6: Sertifikat Pejuang Lingkungan. Lampiran 7: Rubrik penilaian partisipasi dan tanggung jawab."
  },
  {
    tema: "Membantu Teman yang Kesulitan",
    kelompokUsia: "B",
    topikKBC: "Gotong Royong",
    tujuanKBC: "Anak dapat memahami pentingnya empati dan kepedulian terhadap sesama, melaksanakan tindakan nyata untuk membantu teman yang kesulitan, membedakan antara menolong dengan mengganggu, serta menumbuhkan budaya saling membantu dan mendukung di lingkungan sekolah.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak membantu teman sebagai bentuk kasih sayang sesama, memahami bahwa menolong adalah perbuatan yang dicintai Allah, serta berdoa untuk teman yang kesulitan.",
      berkebinekaan_global: "Anak memahami bahwa setiap orang memiliki kesulitan yang berbeda-beda, menghargai berbagai cara orang mengekspresikan kesulitan mereka, serta menghormati teman yang butuh bantuan atau tidak.",
      gotong_royong: "Anak mengamati dan mengenali tanda-tanda teman yang kesulitan, menawarkan bantuan dengan sopan, membantu tanpa mengharapkan imbalan, bekerja sama menyelesaikan masalah teman, serta memberikan dukungan emosional.",
      mandiri_dan_kreatif: "Anak dapat menemukan cara kreatif untuk membantu teman, memecahkan masalah sederhana yang dihadapi teman, mengajak teman lain untuk ikut membantu, serta mempertimbangkan konsekuensi dari setiap tindakan bantuan.",
      bernalar_kritis: "Anak membedakan situasi ketika teman butuh bantuan atau tidak, menganalisis cara bantuan yang tepat untuk setiap situasi, memahami perbedaan antara menolong dan memanjakan, serta mengevaluasi efektivitas bantuan yang diberikan.",
      sehat_jasmani_dan_rohani: "Anak menunjukkan empati melalui ekspresi wajah dan bahasa tubuh, menenangkan teman yang sedih atau cemas, menjaga jarak dan batasan pribadi saat menolong, serta merasakan kebahagiaan saat membantu orang lain.",
      warga_negara: "Anak memahami dirinya sebagai bagian dari komunitas yang saling mendukung, sadar bahwa membantu teman adalah tanggung jawab bersama, serta berkontribusi dalam menciptakan lingkungan yang suportif."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran berbasis empati dan praktik sosial, anak akan:\n1. Memahami konsep empati dan kepedulian terhadap sesama\n2. Mengenali tanda-tanda teman yang membutuhkan bantuan\n3. Mempraktikkan cara menawarkan bantuan dengan sopan dan tepat\n4. Membedakan antara menolong yang baik dan mengganggu\n5. Menunjukkan perilaku gotong royong dalam kegiatan sehari-hari\n6. Menumbuhkan rasa tanggung jawab terhadap teman\n7. Membangun budaya saling membantu di lingkungan sekolah",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 1-2 hari (± 4 jam total) dengan pendekatan social-emotional learning:\n- Pembelajaran berbasis pengalaman sosial dan emosional\n- Metode role playing dan simulasi situasi nyata\n- Pembelajaran kolaboratif melalui diskusi dan refleksi\n- Pembelajaran karakter dan nilai-nilai moral\n- Penilaian berbasis observasi perilaku\n- Integrasi nilai-nilai empati, kepedulian, dan tanggung jawab\n- Lingkungan belajar yang aman, suportif, dan penuh kasih",
    kegiatanPembelajaran: {
      pendahuluan: "Guru memulai dengan cerita tentang seorang anak yang kesulitan dan dibantu oleh temannya. Guru bertanya: 'Apa yang terjadi dalam cerita ini? Bagaimana perasaan anak yang dibantu? Bagaimana perasaan anak yang menolong?' Guru menampilkan gambar-gambar berbagai situasi (teman yang menangis, teman yang terjatuh, teman yang kesulitan mengerjakan tugas). Guru bertanya: 'Dari gambar-gambar ini, siapa yang membutuhkan bantuan? Bagaimana kita tahu?' Guru memperkenalkan tema: 'Hari ini kita akan belajar menjadi teman yang peduli dan suka menolong!'",
      inti: [
        "DISKUSI EMPATI: Guru memimpin diskusi tentang empati. Apa itu empati? Bagaimana rasanya ketika kita sedih dan ada yang menolong? Bagaimana rasanya ketika kita menolong orang lain? Anak berbagi pengalaman pribadi ketika mereka dibantu atau menolong orang lain. Guru mencatat kata-kata kunci di papan (sadar, peduli, tanya, bantu).",
        "SIMULASI SITUASI: Guru dan anak bermain peran (role playing) berbagai situasi: Teman yang jatuh di lapangan, teman yang bingung mengerjakan tugas, teman yang kehilangan barang, teman yang sedang sendirian. Anak mempraktikkan cara menawarkan bantuan: 'Apa yang bisa saya bantu?', 'Apakah kamu butuh bantuan?', 'Mari kita kerjakan bersama.' Guru memberikan umpan balik dan penguatan.",
        "KARTU SITUASI: Guru membagikan kartu-kartu situasi kepada anak secara berpasangan. Setiap kartu berisi skenario (misalnya: 'Temanmu menangis karena kehilangan mainan'). Anak mendiskusikan: Apa yang harus dilakukan? Apa yang harus dikatakan? Setiap pasangan mempresentasikan cara mereka menolong.",
        "PRAKTIK NYATA: Guru mengatur situasi di mana beberapa anak 'dipersiapkan' untuk membutuhkan bantuan (misalnya: menjatuhkan benda, terlihat bingung). Anak lain diamati apakah mereka menawarkan bantuan. Guru mencatat perilaku anak untuk didiskusikan kemudian.",
        "BUKU CERITA: Anak membuat 'Buku Cerita Menolong' mereka sendiri. Setiap halaman berisi gambar situasi ketika mereka menolong seseorang (di sekolah atau di rumah) dan kalimat sederhana yang mendeskripsikan tindakan mereka. Anak dapat mendiktekan cerita kepada guru untuk ditulis."
      ],
      penutup: "Guru mengajak anak duduk melingkar dan memimpin refleksi: 'Hari ini kita belajar banyak cara untuk menolong teman. Situasi mana yang paling mudah bagimu? Situasi mana yang paling sulit? Apa yang akan kamu lakukan berbeda mulai hari ini?' Anak berbagi refleksi. Guru memamerkan 'Buku Cerita Menolong' anak-anak di dinding kelas. Guru memberikan 'Sertifikat Teman Baik' atau 'Bintang Kepedulian' kepada setiap anak. Guru memimpin doa agar selalu diberikan hati yang peduli dan menutup dengan salam dan ucapan terima kasih.",
    },
    lampiran: "Lampiran 1: Kartu-kartu situasi untuk role playing. Lampiran 2: Gambar-gambar berbagai situasi butuh bantuan. Lampiran 3: Template Buku Cerita Menolong. Lampiran 4: Rubrik penilaian observasi perilaku empati. Lampiran 5: Sertifikat Teman Baik. Lampiran 6: Daftar kata-kata kunci empati dan bantuan."
  },
  {
    tema: "Kerja Bakti Membersihkan Lingkungan",
    kelompokUsia: "B",
    topikKBC: "Gotong Royong",
    tujuanKBC: "Anak dapat memahami pentingnya kebersihan lingkungan bagi kesehatan dan kenyamanan, melaksanakan kegiatan kerja bakti secara kolaboratif, membedakan antara sampah organik dan anorganik, serta menumbuhkan rasa tanggung jawab terhadap kebersihan lingkungan sekolah.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak memahami bahwa menjaga kebersihan adalah bagian dari iman, bersyukur kepada Allah atas lingkungan yang bersih dan sehat, serta merawat ciptaan Allah dengan cara membuang sampah pada tempatnya.",
      berkebinekaan_global: "Anak memahami bahwa setiap negara memiliki tantangan sampah yang berbeda, menghargai berbagai cara pengelolaan sampah di berbagai negara, serta menghormati peran pekerja kebersihan di masyarakat.",
      gotong_royong: "Anak bekerja sama dalam kelompok untuk membersihkan area tertentu, membagi tugas secara adil (memungut sampah, menyapu, memilah), membantu teman yang membawa sampah berat, serta saling mengingatkan untuk menjaga kebersihan.",
      mandiri_dan_kreatif: "Anak dapat membedakan sampah organik dan anorganik, membuat tempat sampah kreatif dengan label, menemukan cara daur ulang barang bekas, serta mempraktikkan 3R (Reduce, Reuse, Recycle).",
      bernalar_kritis: "Anak membedakan berbagai jenis sampah dan cara pengolahannya, memahami dampak sampah terhadap lingkungan dan kesehatan, menjelaskan mengapa kita harus memilah sampah, serta mengajukan solusi kreatif untuk pengelolaan sampah.",
      sehat_jasmani_dan_rohani: "Anak bergerak aktif saat kerja bakti (menyapu, memungut, mengangkat), menggunakan alat kebersihan dengan benar dan aman, menjaga kebersihan diri setelah kegiatan, serta merasakan kepuasan melihat lingkungan yang bersih.",
      warga_negara: "Anak memahami dirinya sebagai warga sekolah yang bertanggung jawab atas kebersihan, sadar bahwa kebersihan adalah tanggung jawab bersama, serta berpartisipasi dalam kegiatan lingkungan sekolah."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran berbasis praktik lingkungan, anak akan:\n1. Memahami pentingnya kebersihan lingkungan bagi kesehatan dan kenyamanan\n2. Membedakan antara sampah organik dan anorganik\n3. Mempraktikkan kegiatan kerja bakti secara kolaboratif\n4. Memahami konsep 3R (Reduce, Reuse, Recycle)\n5. Menunjukkan tanggung jawab terhadap kebersihan lingkungan\n6. Menumbuhkan kebiasaan membuang sampah pada tempatnya\n7. Membangun budaya gotong royong dalam menjaga lingkungan",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 1-2 hari (± 4 jam total) dengan pendekatan experiential learning:\n- Pembelajaran berbasis pengalaman langsung dan praktik nyata\n- Metode field learning di area sekolah\n- Pembelajaran kolaboratif melalui kerja kelompok\n- Pembelajaran lintas mata pelajaran (IPA, PKn, kesehatan)\n- Penilaian berbasis proses dan perilaku nyata\n- Integrasi nilai-nilai kebersihan, tanggung jawab, dan gotong royong\n- Lingkungan belajar yang aktif dan berorientasi tindakan",
    kegiatanPembelajaran: {
      pendahuluan: "Guru membawa anak untuk berkeliling lingkungan sekolah. Guru bertanya: 'Apa yang kalian lihat? Apakah ada yang tidak rapi? Apakah ada sampah di sembarang tempat? Bagaimana perasaan kalian melihat lingkungan yang kotor?' Guru menampilkan gambar lingkungan yang bersih dan kotor, lalu meminta anak membandingkan dan memilih mana yang lebih nyaman. Guru mengatakan: 'Jika kita bekerja sama, kita bisa membuat sekolah kita bersih dan sehat! Siapa yang mau ikut kerja bakti?'",
      inti: [
        "PENGENALAN SAMPAH: Guru menampilkan berbagai jenis sampah (daun kering, kertas, botol plastik, sisa makanan, kaleng). Anak diajak mengamati dan mengelompokkan sampah tersebut. Guru memperkenalkan konsep sampah organik (dari alam, bisa membusuk) dan anorganik (dari buatan manusia, sulit membusuk).",
        "GAME PILAH SAMPAH: Guru membuat dua kotak besar dengan label 'Organik' dan 'Anorganik'. Guru menyebarkan sampah contoh di lantai. Anak bergantian mengambil sampah dan memasukkannya ke kotak yang tepat. Setelah selesai, guru dan anak bersama-sama memeriksa apakah semua sampah berada di tempat yang benar.",
        "DEMONSTRASI KERJA BAKTI: Guru mendemonstrasikan cara kerja bakti yang benar: cara menggunakan sapu dengan aman, cara memungut sampah dengan sarung tangan atau alat, cara membawa kantong sampah. Guru menekankan keselamatan dan kebersihan diri.",
        "PRAKTIK KERJA BAKTI: Anak dibagi menjadi beberapa kelompok dengan area berbeda (halaman, kelas, taman). Setiap kelompok mendapat tugas: memungut sampah, menyapu, memilah sampah. Guru berkeliling memfasilitasi dan memastikan keamanan anak. Anak bekerja sama menyelesaikan tugas mereka.",
        "DAUR ULANG KREATIF: Setelah kerja bakti, guru memperkenalkan konsep 3R. Anak membuat karya daur ulang sederhana dari barang bekas yang terkumpul (misalnya: membuat pot dari botol plastik, membuat hiasan dari kertas bekas). Anak dapat membawa karya mereka pulang.",
        "REFLESI SAMPAH: Guru mengajak anak melihat hasil kerja bakti mereka. Guru bertanya: 'Bagaimana perasaan kalian melihat sekolah yang bersih? Apa bedanya dengan sebelum kerja bakti? Apa yang akan kalian lakukan berbeda mulai hari ini?'"
      ],
      penutup: "Guru mengajak anak berkumpul di area yang telah dibersihkan. Guru memimpin doa syukur atas kemampuan untuk bekerja sama dan menjaga lingkungan. Guru memberikan 'Sertifikat Pahlawan Kebersihan' atau 'Bintang Hijau' kepada setiap anak. Guru menutup dengan ajakan: 'Kebersihan adalah tanggung jawab kita semua. Mari kita jaga sekolah kita tetap bersih setiap hari!' Guru dan anak menutup dengan salam dan senyuman bangga.",
    },
    lampiran: "Lampiran 1: Contoh sampah organik dan anorganik. Lampiran 2: Kotak sampah dengan label. Lampiran 3: Alat kerja bakti (sapu, pengki, sarung tangan, kantong sampah). Lampiran 4: Bahan untuk daur ulang kreatif. Lampiran 5: Sertifikat Pahlawan Kebersihan. Lampiran 6: Rubrik penilaian partisipasi dan tanggung jawab. Lampiran 7: Poster 3R (Reduce, Reuse, Recycle)."
  },
  // Pilar 4: Mandiri dan Kreatif (3 templates)
  {
    tema: "Berani Tampil di Depan Umum",
    kelompokUsia: "B",
    topikKBC: "Mandiri dan Kreatif",
    tujuanKBC: "Anak dapat mengembangkan kepercayaan diri untuk tampil di depan umum, mempraktikkan teknik dasar public speaking yang sesuai usia, mengekspresikan ide dan perasaan dengan jelas dan percaya diri, serta mengatasi rasa takut dan cemas saat berbicara di depan orang lain.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak berani tampil dengan niat baik dan jujur, mengucapkan kata-kata yang sopan dan bermartabat, serta bersyukur kepada Allah atas kemampuan yang diberikan.",
      berkebinekaan_global: "Anak menghargai berbagai gaya komunikasi dan ekspresi dari budaya berbeda, memahami bahwa setiap anak memiliki cara unik untuk tampil, serta menghormati teman yang tampil dengan gaya berbeda.",
      gotong_royong: "Anak mendukung dan menyemangati teman yang tampil, memberikan apresiasi dan tepuk tangan untuk setiap penampil, membantu teman yang gugup atau lupa, serta bekerja sama dalam persiapan pertunjukan.",
      mandiri_dan_kreatif: "Anak dapat menyiapkan materi tampilan sendiri, mengatur pernapasan sebelum tampil, menggunakan gerakan tubuh dan ekspresi wajah yang tepat, mempraktikkan teknik eye contact sederhana, serta pulih dengan cepat jika terjadi kesalahan.",
      bernalar_kritis: "Anak membedakan antara tampilan yang baik dan perlu ditingkatkan, menganalisis mengapa beberapa orang lebih percaya diri, memahami pentingnya persiapan sebelum tampil, serta mengevaluasi performa diri dan teman secara konstruktif.",
      sehat_jasmani_dan_rohani: "Anak melakukan teknik pernapasan untuk menenangkan diri, menggunakan postur tubuh yang baik saat tampil, menjaga kesehatan suara dengan cara yang tepat, serta merasakan kepuasan setelah berhasil tampil.",
      warga_negara: "Anak memahami kemampuan berbicara di depan umum sebagai keterampilan penting, berani menyampaikan pendapat dengan sopan, serta berkontribusi dalam diskusi kelas."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran berbasis pengembangan diri, anak akan:\n1. Memahami konsep kepercayaan diri dan public speaking\n2. Mempraktikkan teknik dasar public speaking (pernapasan, postur, suara)\n3. Menyiapkan dan menyampaikan presentasi singkat dengan percaya diri\n4. Mengatasi rasa takut dan cemas saat tampil di depan umum\n5. Menggunakan bahasa tubuh dan ekspresi yang sesuai\n6. Memberikan dan menerima umpan balik secara konstruktif\n7. Menumbuhkan kebiasaan berani tampil di berbagai kesempatan",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 2-3 hari (± 6 jam total) dengan pendekatan performance-based learning:\n- Pembelajaran berbasis praktik dan pengalaman langsung\n- Metode scaffolding dari tampil sederhana ke kompleks\n- Pembelajaran kolaboratif melalui dukungan teman sebaya\n- Pembelajaran karakter dan keterampilan sosial\n- Penilaian berbasis performa dan progres\n- Integrasi nilai-nilai keberanian, kejujuran, dan penghargaan\n- Lingkungan belajar yang aman, suportif, dan non-judgmental",
    kegiatanPembelajaran: {
      pendahuluan: "Guru memulai dengan bertanya: 'Siapa di sini yang suka bercerita? Siapa yang pernah bercerita di depan kelas? Bagaimana perasaannya?' Guru menampilkan video anak-anak yang tampil percaya diri (misalnya dalam kontes cerita, pidato, atau pertunjukan). Guru mengajak anak mengamati: 'Apa yang membuat mereka tampak percaya diri? Bagaimana mereka berdiri? Bagaimana suara mereka?' Guru mengatakan: 'Hari ini kita akan belajar menjadi pembicara yang percaya diri! Setiap dari kalian punya kemampuan untuk tampil hebat!'",
      inti: [
        "TEKNIK DASAR: Guru mengajarkan teknik dasar public speaking yang sesuai usia: (1) Berdiri dengan kedua kaki terbuka lebar bahu, (2) Pandang mata pendengar, (3) Gunakan suara yang jelas dan cukup keras, (4) Gunakan tangan untuk gerakan yang wajar, (5) Senyum dan bersikap positif. Anak mempraktikkan setiap teknik satu per satu dengan bimbingan guru.",
        "LATIHAN PERNAPASAN: Guru mengajarkan teknik pernapasan untuk menenangkan diri: tarik napas dalam-dalam selama 4 detik, tahan selama 4 detik, hembuskan selama 4 detik. Anak mempraktikkan bersama-sama. Guru menjelaskan bahwa teknik ini dapat digunakan saat merasa gugup.",
        "SHOW AND TELL: Setiap anak diminta membawa benda atau foto dari rumah yang ingin mereka ceritakan. Satu per satu, anak tampil di depan kelas selama 1-2 menit untuk menceritakan tentang benda tersebut. Guru dan teman memberikan tepuk tangan dan apresiasi setelah setiap penampilan.",
        "CERITA BERSAMA: Anak dibagi menjadi kelompok kecil. Setiap kelompok diberikan gambar sebagai pemicu cerita. Kelompok berdiskusi dan menyusun cerita sederhana. Setiap kelompok memilih satu wakil untuk menceritakan di depan kelas. Guru memberikan umpan balik positif.",
        "MICRO PRESENTASI: Anak menyiapkan presentasi singkat (30-60 detik) tentang topik favorit mereka (hobi, makanan kesukaan, keluarga, dll). Anak berlatih dengan pasangan, kemudian tampil di depan kelas. Guru mencatat kekuatan dan area yang perlu dikembangkan untuk setiap anak.",
        "UMBAL BALIK: Setelah semua anak tampil, guru memimpin diskusi tentang pengalaman mereka. 'Apa yang paling kamu sukai dari tampil di depan? Apa yang paling menantang? Apa yang akan kamu lakukan berbeda next time?' Guru memberikan catatan pribadi dan saran untuk setiap anak."
      ],
      penutup: "Guru mengajak anak duduk melingkar. Guru memuji keberanian setiap anak yang telah tampil, tidak peduli seberapa sempurna penampilannya. Guru memberikan 'Sertifikat Pembicara Cilik' atau 'Bintang Keberanian' kepada setiap anak dengan catatan khusus tentang kekuatan mereka. Guru memimpin doa syukur atas kemampuan yang diberikan Allah dan menutup dengan ajakan: 'Teruslah berlatih dan berani tampil! Kalian semua luar biasa!' Guru dan anak menutup dengan tepuk tangan meriah untuk semua.",
    },
    lampiran: "Lampiran 1: Video anak-anak yang tampil percaya diri. Lampiran 2: Gambar-gambar pemicu cerita. Lampiran 3: Rubrik penilaian performa public speaking. Lampiran 4: Template sertifikat Pembicara Cilik. Lampiran 5: Catatan umpan balik individual. Lampiran 6: Poster teknik dasar public speaking."
  },
  {
    tema: "Membuat Karya Seni Sendiri",
    kelompokUsia: "B",
    topikKBC: "Mandiri dan Kreatif",
    tujuanKBC: "Anak dapat mengekspresikan kreativitas melalui berbagai media seni, membuat karya seni orisinal dengan imajinasi sendiri, mempraktikkan teknik seni dasar yang sesuai usia, serta menumbuhkan rasa bangga dan percaya diri terhadap kemampuan kreatif mereka.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak bersyukur kepada Allah atas kemampuan kreatif yang diberikan, mengekspresikan keindahan ciptaan Allah melalui seni, serta menggunakan karya seni untuk menyebarkan kebaikan dan keindahan.",
      berkebinekaan_global: "Anak menghargai berbagai gaya seni dari budaya berbeda, memahami bahwa setiap orang memiliki gaya seni yang unik, serta menghormati perbedaan dalam ekspresi artistik.",
      gotong_royong: "Anak berbagi ide dan inspirasi dengan teman, membantu teman yang kesulitan dalam berkarya, memberikan apresiasi dan komentar positif untuk karya teman, serta bekerja sama dalam proyek seni kelompok.",
      mandiri_dan_kreatif: "Anak dapat menghasilkan ide-ide kreatif sendiri, memilih media dan teknik yang sesuai dengan ide mereka, memecahkan masalah yang muncul saat berkarya, menyelesaikan karya dengan mandiri, serta mempresentasikan karya dengan percaya diri.",
      bernalar_kritis: "Anak menganalisis komposisi dan warna dalam karya seni, membedakan berbagai teknik seni dan efeknya, menjelaskan alasan di balik pilihan artistik mereka, serta mengevaluasi karya sendiri dan teman secara konstruktif.",
      sehat_jasmani_dan_rohani: "Anak menggunakan motorik halus saat berkarya (menggambar, melukis, merangkai), menjaga kebersihan saat bekerja dengan cat dan bahan seni, menikmati proses berkarya dengan ketenangan dan kebahagiaan, serta merasakan kepuasan melihat hasil karya.",
      warga_negara: "Anak memahami seni sebagai bagian dari budaya bangsa, bangga dengan karya seni Indonesia, serta menyadari peran seni dalam kehidupan masyarakat."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran berbasis seni dan kreativitas, anak akan:\n1. Mengekspresikan ide dan imajinasi melalui berbagai media seni\n2. Mempraktikkan teknik seni dasar (menggambar, melukis, kolase, origami)\n3. Membuat karya seni orisinal dengan gaya sendiri\n4. Memecahkan masalah kreatif yang muncul saat berkarya\n5. Menjelaskan karya seni mereka dengan kata-kata sendiri\n6. Memberikan dan menerima apresiasi terhadap karya seni\n7. Menumbuhkan rasa bangga dan percaya diri terhadap kemampuan kreatif",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 2-3 hari (± 6 jam total) dengan pendekatan arts-based learning:\n- Pembelajaran berbasis eksplorasi dan ekspresi artistik\n- Metode open-ended art activities\n- Pembelajaran individual dan kolaboratif\n- Pembelajaran lintas mata pelajaran (seni, bahasa, matematika)\n- Penilaian berbasis proses dan produk kreatif\n- Integrasi nilai-nilai kreativitas, kebebasan berekspresi, dan apresiasi\n- Lingkungan belajar yang kaya warna, inspiratif, dan non-judgmental",
    kegiatanPembelajaran: {
      pendahuluan: "Guru memulai dengan memamerkan berbagai karya seni anak (lukisan, kolase, origami, patung tanah liat). Guru bertanya: 'Karya mana yang paling kamu suka? Mengapa? Apa yang kamu lihat dari karya ini?' Guru menampilkan karya seni terkenal yang sesuai usia anak (karya seniman anak, ilustrasi buku anak). Guru mengatakan: 'Setiap orang bisa membuat karya seni yang indah! Hari ini kalian akan menjadi seniman cilik dan membuat karya seni kalian sendiri!'",
      inti: [
        "EKSPLORASI MEDIA: Guru menyediakan berbagai media seni (krayon, cat air, cat minyak, pastel, kertas warna, kertas bekas, tanah liat, bahan alam seperti daun dan batu). Anak diajak mengeksplorasi setiap media: mencoba menggambar dengan berbagai alat, mencampur warna, merasakan tekstur berbagai bahan. Guru memfasilitasi eksplorasi dan menjawab pertanyaan anak.",
        "TEKNIK DASAR: Guru mendemonstrasikan teknik dasar seni: (1) Menggambar garis dan bentuk, (2) Mencampur warna primer untuk membuat warna sekunder, (3) Membuat kolase dengan menempel kertas, (4) Melukis dengan kuas dan spons. Anak mempraktikkan setiap teknik dengan bimbingan guru.",
        "PROYEK BEBAS: Guru memberikan kebebasan kepada anak untuk membuat karya seni orisinal mereka sendiri. Anak dapat memilih media dan teknik yang mereka sukai. Satu-satunya aturan adalah: karya harus 100% ide dan eksekusi anak sendiri. Guru berkeliling memberikan dukungan, bukan arahan, dan mengajukan pertanyaan pemicu: 'Ceritakan tentang karyamu', 'Apa yang kamu coba ekspresikan?'",
        "PROYEK TERSTRUKTUR (Pilihan): Untuk anak yang membutuhkan lebih banyak struktur, guru menyediakan beberapa proyek terstruktur: (a) Lukis hewan favoritmu, (b) Buat kolase keluargamu, (c) Buat origami hewan, (d) Buat patung tanah liat. Anak dapat memilih salah satu atau membuat proyek sendiri.",
        "WORKSHOP TEMAN: Setelah anak menyelesaikan karya pertama, guru mengatur 'Workshop Teman' di mana anak dapat melihat karya teman lain, bertanya tentang teknik yang digunakan, dan berbagi tips. Guru memfasilitasi diskusi dan memastikan semua komentar positif dan suportif.",
        "FINISHING & SIGNATURE: Anak menyelesaikan karya mereka dengan sentuhan terakhir (menambah detail, membersihkan area, memasang karya di karton). Anak diminta menandatangani karya mereka dengan nama dan tanggal sebagai tanda kepemilikan dan kebanggaan."
      ],
      penutup: "Guru mengadakan 'Pameran Seni Cilik' di mana setiap anak memamerkan karya mereka. Anak berdiri di sebelah karya mereka dan siap menjelaskan kepada pengunjung (teman lain, guru). Guru memimpin 'Gallery Walk' di mana semua anak berjalan melihat semua karya dan memberikan komentar positif. Guru memberikan 'Sertifikat Seniman Cilik' atau 'Bintang Kreativitas' kepada setiap anak dengan catatan khusus tentang kekuatan karya mereka. Guru memimpin doa syukur atas kemampuan kreatif yang diberikan Allah dan menutup dengan tepuk tangan meriah untuk semua karya.",
    },
    lampiran: "Lampiran 1: Berbagai media seni (krayon, cat air, pastel, kertas warna, tanah liat). Lampiran 2: Contoh karya seni anak dan seniman terkenal. Lampiran 3: Template proyek terstruktur. Lampiran 4: Karton untuk mounting karya. Lampiran 5: Sertifikat Seniman Cilik. Lampiran 6: Rubrik penilaian kreativitas dan proses. Lampiran 7: Poster tips kreativitas."
  },
  {
    tema: "Mengelola Keuangan Cilik (Tabung, Belanja, Bagi)",
    kelompokUsia: "B",
    topikKBC: "Mandiri dan Kreatif",
    tujuanKBC: "Anak dapat memahami konsep dasar pengelolaan uang (uang didapat, ditabung, dibelanjakan, dan dibagikan), mempraktikkan pembagian uang menjadi tiga bagian (tabung, belanja, bagi), membuat keputusan sederhana tentang penggunaan uang, serta menumbuhkan kebiasaan menabung dan berbagi sejak dini.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak memahami uang sebagai nikmat dari Allah yang harus digunakan dengan bijak, bersyukur atas uang yang dimiliki, serta berbagi sebagian uang untuk kebaikan (sedekah) sebagai bentuk kasih sayang.",
      berkebinekaan_global: "Anak memahami bahwa setiap keluarga memiliki kondisi keuangan berbeda, menghargai berbagai cara pengelolaan uang di berbagai budaya, serta tidak menghakimi teman berdasarkan kondisi keuangan.",
      gotong_royong: "Anak berbagi uang untuk kebaikan bersama (kotak amal, bantuan teman), membantu teman memahami konsep menabung, serta mendukung kegiatan kelas yang membutuhkan dana.",
      mandiri_dan_kreatif: "Anak dapat membedakan antara kebutuhan dan keinginan, membuat keputusan sederhana tentang pembelian, menghitung uang sederhana, menggunakan celengan dengan mandiri, serta merencanakan penggunaan uang.",
      bernalar_kritis: "Anak membedakan antara barang yang perlu dan yang hanya diinginkan, menganalisis konsekuensi dari setiap keputusan pembelian, memahami konsep 'hemat' dan 'boros', serta mengevaluasi penggunaan uang mereka.",
      sehat_jasmani_dan_rohani: "Anak menjaga kesehatan mental dengan tidak obsesi terhadap barang, menikmati kebahagiaan sederhana tanpa harus belanja, merasakan kepuasan saat menabung dan berbagi, serta menjaga keseimbangan antara menabung dan menggunakan uang.",
      warga_negara: "Anak memahami peran uang dalam masyarakat, sadar bahwa uang adalah alat transaksi, serta memahami pentingnya menabung untuk masa depan."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran berbasis literasi keuangan, anak akan:\n1. Memahami sumber-sumber uang (hadiah, upah, belanja orang tua)\n2. Mempraktikkan konsep 3B (Bagi, Belanja, Tabung)\n3. Membedakan antara kebutuhan dan keinginan\n4. Membuat keputusan sederhana tentang penggunaan uang\n5. Menghitung dan mengelola uang sederhana\n6. Menumbuhkan kebiasaan menabung dan berbagi\n7. Memahami nilai uang dan cara penggunaannya yang bijak",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 2 hari (± 4 jam total) dengan pendekatan experiential learning:\n- Pembelajaran berbasis simulasi dan praktik nyata\n- Metode permainan dan role playing\n- Pembelajaran kolaboratif melalui diskusi dan berbagi pengalaman\n- Pembelajaran matematika dan karakter secara terintegrasi\n- Penilaian berbasis perilaku dan keputusan\n- Integrasi nilai-nilai kebijaksanaan, hemat, dan kepedulian\n- Lingkungan belajar yang praktis dan relevan dengan kehidupan anak",
    kegiatanPembelajaran: {
      pendahuluan: "Guru memulai dengan menampilkan uang kertas dan koin (asli atau mainan). Guru bertanya: 'Apa ini? Apa fungsinya? Dari mana uang berasal? Apa yang bisa kita lakukan dengan uang?' Guru menampilkan gambar berbagai barang (mainan, makanan, pakaian, buku). Guru bertanya: 'Mana yang paling kamu inginkan? Mana yang benar-benar kamu butuhkan?' Guru memperkenalkan tema: 'Hari ini kita akan belajar mengelola uang dengan bijak! Uang bukan untuk dibelanjakan semua, tetapi untuk ditabung dan dibagikan juga!'",
      inti: [
        "KONSEP 3B: Guru memperkenalkan konsep 3B - Bagi, Belanja, Tabung. Guru menjelaskan: (1) BAGI: Berbagi sebagian uang untuk kebaikan (sedekah, membantu orang lain), (2) BELANJA: Menggunakan uang untuk membeli barang yang dibutuhkan, (3) TABUNG: Menyimpan sebagian uang untuk masa depan. Guru menampilkan celengan dengan tiga bagian atau tiga celengan terpisah.",
        "SIMULASI UANG: Guru memberikan uang mainan kepada setiap anak (misalnya Rp 10.000). Guru meminta anak membagi uang tersebut menjadi 3 bagian sesuai konsep 3B. Anak berdiskusi: Berapa untuk Bagi? Berapa untuk Belanja? Berapa untuk Tabung? Tidak ada jawaban salah, yang penting anak bisa menjelaskan alasannya.",
        "GAME KEBUTUHAN VS INGINAN: Guru menampilkan kartu-kartu gambar barang (makanan, air, mainan, permen, buku, sepatu baru, mainan mahal, dll). Anak dibagi menjadi dua kelompok: Kelompok Kebutuhan dan Kelompok Inginan. Setiap kartu dibagikan dan kelompok harus menentukan apakah barang tersebut kebutuhan atau inginan. Guru memfasilitasi diskusi dan menjelaskan perbedaan.",
        "TOKO MAINAN: Guru membuat 'Toko Mainan' sederhana dengan barang-barang (mainan, buku, permen) dan harga yang terjangkau. Anak menggunakan uang mainan mereka untuk berbelanja. Guru mengamati keputusan anak: Apakah mereka membeli barang yang dibutuhkan atau yang diinginkan? Apakah mereka menabung sisanya?",
        "PROYEK CELENGAN: Anak membuat 'Celengan 3B' mereka sendiri. Guru menyediakan kaleng atau kotak kosong, kertas warna, dan alat tulis. Anak menghias dan menandai celengan mereka dengan tiga bagian: BAGI, BELANJA, TABUNG. Anak dapat membawa celengan mereka pulang dan mulai praktik di rumah.",
        "CERITA BERBAGI: Guru menceritakan kisah tentang anak yang menabung dan berbagi. Misalnya, kisah tentang anak yang menabung untuk membeli hadiah untuk ibu, atau anak yang berbagi sebagian uangnya untuk membantu teman yang membutuhkan. Anak berdiskusi: Apa yang bisa kita pelajari dari kisah ini?"
      ],
      penutup: "Guru mengajak anak duduk melingkar. Setiap anak memamerkan 'Celengan 3B' yang mereka buat dan menjelaskan rencana penggunaannya. Guru memimpin refleksi: 'Apa yang paling kamu pelajari hari ini? Apa yang akan kamu lakukan berbeda dengan uang kamu?' Anak berbagi refleksi dan rencana. Guru memberikan 'Sertifikat Ahli Keuangan Cilik' atau 'Bintang Tabungan' kepada setiap anak. Guru memimpin doa syukur atas rezeki yang diberikan Allah dan menutup dengan ajakan: 'Mari kita belajar mengelola uang dengan bijak, menabung, dan berbagi!'",
    },
    lampiran: "Lampiran 1: Uang mainan (kertas dan koin). Lampiran 2: Celengan atau kaleng untuk proyek. Lampiran 3: Kartu-kartu gambar barang (kebutuhan vs inginan). Lampiran 4: Barang untuk 'Toko Mainan'. Lampiran 5: Sertifikat Ahli Keuangan Cilik. Lampiran 6: Rubrik penilaian keputusan dan pemahaman. Lampiran 7: Poster konsep 3B."
  },
  // Pilar 5: Bernalar Kritis (3 templates)
  {
    tema: "Eksperimen Sains Sederhana",
    kelompokUsia: "B",
    topikKBC: "Bernalar Kritis",
    tujuanKBC: "Anak dapat mengembangkan kemampuan berpikir kritis melalui eksperimen sains sederhana, membuat prediksi dan hipotesis, mengamati dan mencatat hasil, menarik kesimpulan dari pengamatan, serta menumbuhkan rasa ingin tahu dan kecintaan terhadap ilmu pengetahuan.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak bersyukur kepada Allah atas keajaiban alam dan ilmu pengetahuan, memahami bahwa menuntut ilmu adalah ibadah, serta menggunakan ilmu untuk kebaikan dan bukan keburukan.",
      berkebinekaan_global: "Anak memahami bahwa ilmu pengetahuan milik semua manusia, menghargai kontribusi ilmuwan dari berbagai negara, serta menghormati perbedaan pendapat dalam proses ilmiah.",
      gotong_royong: "Anak bekerja sama dalam kelompok untuk melakukan eksperimen, berbagi alat dan bahan, membantu teman yang kesulitan, mendiskusikan hasil bersama, serta merayakan keberhasilan tim.",
      mandiri_dan_kreatif: "Anak dapat membuat prediksi dan hipotesis sendiri, merancang eksperimen sederhana, mencatat pengamatan dengan cara mereka sendiri (gambar, tulisan, simbol), menarik kesimpulan dari hasil, serta mengajukan pertanyaan lanjutan.",
      bernalar_kritis: "Anak membedakan antara fakta dan opini, menganalisis sebab-akibat dalam eksperimen, membandingkan hasil prediksi dan kenyataan, menjelaskan alasan di balik setiap hasil eksperimen, serta mengajukan pertanyaan 'apa' dan 'mengapa'.",
      sehat_jasmani_dan_rohani: "Anak menggunakan motorik halus saat melakukan eksperimen (menuang, mencampur, mengukur), menjaga keamanan saat bekerja dengan bahan tertentu, menikmati proses penemuan dengan kegembiraan, serta merasakan kepuasan intelektual saat memahami sesuatu.",
      warga_negara: "Anak memahami pentingnya ilmu pengetahuan bagi kemajuan bangsa, bangga dengan ilmuwan Indonesia, serta menyadari bahwa setiap anak bisa menjadi ilmuwan."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran berbasis inkuiri sains, anak akan:\n1. Memahami langkah-langkah metode ilmiah sederhana (amati, tanya, prediksi, eksperimen, kesimpulan)\n2. Membuat prediksi dan hipotesis sebelum eksperimen\n3. Melakukan eksperimen sains sederhana dengan bahan aman\n4. Mengamati dan mencatat hasil pengamatan dengan sistematis\n5. Menganalisis hasil dan menarik kesimpulan\n6. Mengkomunikasikan hasil eksperimen kepada orang lain\n7. Menumbuhkan rasa ingin tahu dan kecintaan terhadap sains",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 2-3 hari (± 6 jam total) dengan pendekatan inquiry-based learning:\n- Pembelajaran berbasis penemuan dan eksplorasi\n- Metode scientific thinking yang disederhanakan\n- Pembelajaran kolaboratif melalui kerja kelompok\n- Pembelajaran lintas mata pelajaran (sains, matematika, bahasa)\n- Penilaian berbasis proses ilmiah dan hasil\n- Integrasi nilai-nilai kejujuran, ketelitian, dan kerja sama\n- Lingkungan belajar yang penuh keajaiban dan penemuan",
    kegiatanPembelajaran: {
      pendahuluan: "Guru memulai dengan demonstrasi sains yang menarik (misalnya: membalikkan gelas berisi air tanpa tumpah, atau membuat gunung berapi dari soda dan baking soda). Guru bertanya: 'Apa yang kalian lihat? Apa yang kira-kira akan terjadi? Mengapa hal itu bisa terjadi?' Guru menampilkan gambar ilmuwan dan laboratorium. Guru mengatakan: 'Hari ini kita semua akan menjadi ilmuwan cilik! Kita akan melakukan eksperimen dan menemukan keajaiban sains!'",
      inti: [
        "PENGENALAN METODE ILMIAH: Guru memperkenalkan langkah-langkah metode ilmiah sederhana: (1) AMATI: Lihat dan perhatikan sesuatu, (2) TANYA: Ajukan pertanyaan, (3) PREDIKSI: Tebak apa yang akan terjadi, (4) EKSPERIMEN: Coba dan lakukan, (5) KESIMPULAN: Apa yang kita pelajari? Guru menuliskan langkah-langkah ini di papan dengan ikon yang jelas.",
        "EKSPERIMEN 1 - CAMPURAN WARNA: Guru menyediakan air dengan warna primer (merah, biru, kuning). Anak diminta memprediksi: 'Apa yang akan terjadi jika kita mencampur merah dan biru?' Anak mencatat prediksi mereka. Anak melakukan eksperimen: menuang warna merah dan biru ke dalam gelas transparan. Anak mengamati dan mencatat hasil. Anak menarik kesimpulan: 'Merah + Biru = Ungu.' Proses diulang untuk kombinasi warna lain.",
        "EKSPERIMEN 2 - MENGAPATUR BENDA MENGAMBANG/TENGGELAM: Guru menyediakan berbagai benda (batu, kayu, koin, busa, plastik, kertas) dan wadah berisi air. Anak diminta memprediksi benda mana yang akan mengambang dan mana yang akan tenggelam. Anak mencatat prediksi. Anak melakukan eksperimen: memasukkan setiap benda ke dalam air. Anak mengamati dan mencatat hasil. Anak menganalisis: Mengapa beberapa benda mengambang dan lainnya tenggelam?",
        "EKSPERIMEN 3 - TANAMAN DAN CAHAYA: Jika memungkinkan, Guru menyiapkan dua tanaman yang sama: satu diletakkan di tempat terang dan satu di tempat gelap. Anak diminta memprediksi perbedaan yang akan terjadi setelah beberapa hari. Anak mengamati dan mencatat perbedaan (warna daun, tinggi tanaman, kesehatan tanaman). Anak menarik kesimpulan tentang pentingnya cahaya bagi tanaman.",
        "JURNAL EKSPERIMEN: Anak membuat 'Jurnal Eksperimen' mereka sendiri. Setiap halaman berisi: (1) Nama eksperimen, (2) Pertanyaan, (3) Prediksi, (4) Bahan dan alat, (5) Langkah-langkah, (6) Hasil pengamatan (gambar atau tulisan), (7) Kesimpulan. Anak dapat menggambar atau mendiktekan kepada guru untuk ditulis.",
        "PRESENTASI HASIL: Setiap anak atau kelompok mempresentasikan hasil eksperimen mereka di depan kelas. Anak menjelaskan: 'Eksperimen kami adalah... Kami memprediksi... Hasilnya adalah... Kesimpulan kami adalah...' Guru dan teman mengajukan pertanyaan dan memberikan apresiasi."
      ],
      penutup: "Guru mengajak anak berkumpul dan memimpin refleksi: 'Eksperimen mana yang paling kamu sukai? Apa yang paling mengejutkan? Apa yang kamu pelajari tentang menjadi ilmuwan?' Anak berbagi pengalaman dan penemuan mereka. Guru menampilkan 'Jurnal Eksperimen' anak-anak di dinding kelas sebagai 'Laboratorium Kita'. Guru memberikan 'Sertifikat Ilmuwan Cilik' atau 'Bintang Sains' kepada setiap anak dengan catatan khusus tentang kekuatan mereka (misalnya: 'Prediksi yang akurat', 'Pengamatan yang teliti', 'Kesimpulan yang jelas'). Guru memimpin doa syukur atas keajaiban ilmu pengetahuan yang diberikan Allah dan menutup dengan ajakan: 'Teruslah bertanya dan bereksperimen! Kalian semua adalah ilmuwan hebat!'",
    },
    lampiran: "Lampiran 1: Bahan-bahan untuk eksperimen warna (air, pewarna makanan, gelas transparan). Lampiran 2: Berbagai benda untuk eksperimen mengambang/tenggelam. Lampiran 3: Tanaman untuk eksperimen cahaya. Lampiran 4: Template Jurnal Eksperimen. Lampiran 5: Poster langkah-langkah metode ilmiah. Lampiran 6: Sertifikat Ilmuwan Cilik. Lampiran 7: Rubrik penilaian proses ilmiah."
  },
  {
    tema: "Memecahkan Masalah Sehari-hari",
    kelompokUsia: "B",
    topikKBC: "Bernalar Kritis",
    tujuanKBC: "Anak dapat mengembangkan kemampuan memecahkan masalah melalui pemikiran kritis, mengidentifikasi masalah sederhana dalam kehidupan sehari-hari, menemukan beberapa solusi yang mungkin, mengevaluasi solusi dan memilih yang terbaik, serta mempraktikkan solusi yang dipilih.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak memohon bantuan dan petunjuk Allah saat menghadapi masalah, bersabar dan tidak putus asa, menggunakan solusi yang halal dan baik, serta bersyukur ketika masalah terpecahkan.",
      berkebinekaan_global: "Anak memahami bahwa setiap orang menghadapi masalah berbeda, menghargai berbagai cara memecahkan masalah di berbagai budaya, serta menghormati solusi yang dipilih orang lain.",
      gotong_royong: "Anak membantu teman yang menghadapi masalah, bekerja sama menemukan solusi, berbagi pengalaman dan tips, serta mendukung teman saat menghadapi kesulitan.",
      mandiri_dan_kreatif: "Anak dapat mengidentifikasi masalah mereka sendiri, memikirkan beberapa solusi yang mungkin, mengevaluasi pro dan kontra setiap solusi, memilih solusi terbaik, serta melaksanakan solusi dengan mandiri.",
      bernalar_kritis: "Anak menganalisis penyebab masalah, membedakan antara masalah kecil dan besar, menilai kelayakan setiap solusi, memprediksi konsekuensi setiap solusi, serta mengevaluasi keberhasilan solusi yang dipilih.",
      sehat_jasmani_dan_rohani: "Anak mengelola emosi saat menghadapi masalah (tidak marah, tidak menangis), menggunakan teknik menenangkan diri, menjaga kesehatan mental saat stres, serta merasakan kepuasan ketika masalah terpecahkan.",
      warga_negara: "Anak memahami bahwa memecahkan masalah adalah keterampilan penting dalam kehidupan, sadar bahwa masalah adalah bagian dari kehidupan, serta siap menghadapi tantangan di masa depan."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran berbasis pemecahan masalah, anak akan:\n1. Mengidentifikasi masalah sederhana dalam kehidupan sehari-hari\n2. Menganalisis penyebab masalah\n3. Memikirkan beberapa solusi yang mungkin\n4. Mengevaluasi setiap solusi (pro dan kontra)\n5. Memilih solusi terbaik\n6. Mempraktikkan solusi yang dipilih\n7. Mengevaluasi keberhasilan solusi",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 2 hari (± 4 jam total) dengan pendekatan problem-based learning:\n- Pembelajaran berbasis masalah nyata yang relevan dengan anak\n- Metode brainstorming dan diskusi\n- Pembelajaran kolaboratif melalui kerja kelompok\n- Pembelajaran karakter dan keterampilan sosial\n- Penilaian berbasis proses pemecahan masalah\n- Integrasi nilai-nilai ketekunan, kesabaran, dan kreativitas\n- Lingkungan belajar yang suportif dan mendorong pemikiran",
    kegiatanPembelajaran: {
      pendahuluan: "Guru memulai dengan bertanya: 'Pernahkah kalian menghadapi masalah? Apa itu? Apa yang kalian lakukan?' Guru menceritakan kisah tentang anak yang menghadapi masalah dan berhasil memecahkannya. Guru menampilkan gambar-gambar situasi bermasalah (mainan rusak, kehilangan barang, teman bertengkar, tidak bisa mengerjakan tugas). Guru bertanya: 'Masalah apa yang kalian lihat? Apa yang bisa dilakukan?' Guru memperkenalkan tema: 'Hari ini kita akan belajar menjadi pemecah masalah yang hebat! Setiap masalah pasti ada solusinya!'",
      inti: [
        "LANGKAH-LANGKAH PEMECAHAN MASALAH: Guru memperkenalkan 5 langkah pemecahan masalah: (1) KENALI: Apa masalahnya?, (2) PIKIRKAN: Apa penyebabnya?, (3) TEMUKAN: Apa solusinya?, (4) PILIH: Solusi mana yang terbaik?, (5) LAKSANAKAN: Praktikkan solusinya! Guru menuliskan langkah-langkah ini di papan dengan ikon yang jelas.",
        "STUDI KASUS: Guru menampilkan situasi bermasalah: 'Budi kehilangan buku favoritnya di kelas. Dia sangat sedih. Apa yang Budi harus lakukan?' Anak berdiskusi dalam kelompok: Apa masalah Budi? Apa penyebabnya? Apa solusi yang mungkin? (Mencari di kelas, bertanya teman, bertanya guru, mencari di rumah, membeli baru). Setiap kelompok mempresentasikan solusi terbaik mereka beserta alasannya.",
        "BRAINSTORMING SOLUSI: Guru membagikan kartu-kartu situasi bermasalah kepada anak secara berpasangan. Setiap kartu berisi skenario (misalnya: 'Mainanmu rusak', 'Tugasmu terlalu banyak', 'Temanmu tidak mau bermain denganmu'). Anak mendiskusikan dan menuliskan minimal 3 solusi yang mungkin. Setiap pasangan mempresentasikan solusi-solusi mereka.",
        "EVALUASI SOLUSI: Guru mengajarkan cara mengevaluasi solusi: (1) Apakah solusi ini aman?, (2) Apakah solusi ini jujur?, (3) Apakah solusi ini bisa dilakukan?, (4) Apakah solusi ini adil? Anak mempraktikkan mengevaluasi solusi dari studi kasus sebelumnya menggunakan kriteria ini.",
        "PRAKTIK NYATA: Anak diminta memikirkan masalah nyata yang mereka hadapi saat ini (di sekolah atau di rumah). Anak menuliskan atau mendiktekan kepada guru: (1) Masalahnya, (2) Penyebabnya, (3) 3 solusi yang mungkin, (4) Solusi terbaik, (5) Cara melaksanakannya. Anak berbagi dengan teman sebaya untuk mendapatkan masukan.",
        "ROLE PLAYING: Anak bermain peran situasi bermasalah dan solusinya. Misalnya, satu anak bermain sebagai 'anak yang kehilangan barang' dan anak lain bermain sebagai 'teman yang membantu memecahkan masalah'. Anak mempraktikkan langkah-langkah pemecahan masalah yang telah dipelajari."
      ],
      penutup: "Guru mengajak anak duduk melingkar dan memimpin refleksi: 'Masalah apa yang paling sulit bagimu? Solusi mana yang paling kreatif? Apa yang akan kamu lakukan berbeda saat menghadapi masalah?' Anak berbagi pengalaman dan pembelajaran. Guru memberikan 'Sertifikat Pemecah Masalah Cilik' atau 'Bintang Solusi' kepada setiap anak dengan catatan khusus tentang kekuatan mereka (misalnya: 'Pemikiran kreatif', 'Analisis yang baik', 'Ketekunan'). Guru memimpin doa agar selalu diberikan kemampuan untuk memecahkan masalah dengan bijaksana dan menutup dengan ajakan: 'Jangan takut menghadapi masalah! Setiap masalah adalah kesempatan untuk belajar dan menjadi lebih kuat!'",
    },
    lampiran: "Lampiran 1: Kartu-kartu situasi bermasalah. Lampiran 2: Poster langkah-langkah pemecahan masalah. Lampiran 3: Template lembar kerja pemecahan masalah. Lampiran 4: Rubrik penilaian proses pemecahan masalah. Lampiran 5: Sertifikat Pemecah Masalah Cilik. Lampiran 6: Contoh studi kasus tambahan."
  },
  {
    tema: "Mengajukan Pertanyaan yang Baik",
    kelompokUsia: "B",
    topikKBC: "Bernalar Kritis",
    tujuanKBC: "Anak dapat mengembangkan kemampuan berpikir kritis melalui mengajukan pertanyaan yang baik, membedakan antara pertanyaan yang baik dan kurang baik, menggunakan kata tanya (apa, siapa, kapan, di mana, mengapa, bagaimana) dengan tepat, menumbuhkan rasa ingin tahu dan kebiasaan bertanya, serta menghargai pertanyaan orang lain.",
    tujuanProfilLulusan: {
      beriman_dan_berakhlak_mulia: "Anak bertanya untuk memahami agama dan kehidupan, memahami bahwa bertanya adalah cara untuk mendekatkan diri kepada Allah, serta bertanya dengan sopan dan menghormati orang yang ditanya.",
      berkebinekaan_global: "Anak menghargai pertanyaan dari berbagai budaya, memahami bahwa setiap orang memiliki cara bertanya yang berbeda, serta menghormati perbedaan dalam ekspresi rasa ingin tahu.",
      gotong_royong: "Anak mendengarkan pertanyaan teman dengan sopan, membantu teman menjawab pertanyaan, berbagi ide dan informasi, serta menghargai kontribusi setiap orang dalam diskusi.",
      mandiri_dan_kreatif: "Anak dapat mengajukan pertanyaan berdasarkan rasa ingin tahu mereka sendiri, menggunakan kata tanya dengan tepat, memformulasikan pertanyaan yang jelas dan spesifik, mencari jawaban melalui berbagai sumber, serta mengevaluasi kualitas pertanyaan mereka.",
      bernalar_kritis: "Anak membedakan antara pertanyaan faktual dan opini, menganalisis apakah pertanyaan relevan dan penting, menilai apakah pertanyaan dapat dijawab, memahami perbedaan antara pertanyaan 'apa', 'mengapa', dan 'bagaimana', serta merefleksikan kualitas pertanyaan mereka.",
      sehat_jasmani_dan_rohani: "Anak menggunakan bahasa tubuh yang sopan saat bertanya, menjaga nada suara yang sesuai, merasa nyaman mengajukan pertanyaan, serta menikmati proses belajar melalui bertanya.",
      warga_negara: "Anak memahami bahwa mengajukan pertanyaan adalah hak setiap warga negara, berani bertanya untuk memahami hal-hal di sekitarnya, serta berkontribusi dalam diskusi demokratis."
    },
    tujuanPembelajaranMendalam: "Melalui kegiatan pembelajaran berbasis inkuiri dan tanya jawab, anak akan:\n1. Memahami pentingnya mengajukan pertanyaan dalam pembelajaran\n2. Menggunakan kata tanya (apa, siapa, kapan, di mana, mengapa, bagaimana) dengan tepat\n3. Membedakan antara pertanyaan yang baik dan kurang baik\n4. Memformulasikan pertanyaan yang jelas, spesifik, dan relevan\n5. Mengajukan pertanyaan dengan sopan dan percaya diri\n6. Mencari dan mengevaluasi jawaban untuk pertanyaan mereka\n7. Menumbuhkan kebiasaan bertanya dan rasa ingin tahu",
    kerangkaPembelajaran: "Pembelajaran berlangsung selama 1-2 hari (± 4 jam total) dengan pendekatan inquiry-based learning:\n- Pembelajaran berbasis tanya jawab dan eksplorasi\n- Metode Socratic questioning yang disederhanakan\n- Pembelajaran kolaboratif melalui diskusi dan berbagi\n- Pembelajaran bahasa dan berpikir kritis secara terintegrasi\n- Penilaian berbasis kualitas pertanyaan dan partisipasi\n- Integrasi nilai-nilai keberanian, rasa hormat, dan keingintahuan\n- Lingkungan belajar yang mendorong pertanyaan dan eksplorasi",
    kegiatanPembelajaran: {
      pendahuluan: "Guru memulai dengan memunculkan rasa ingin tahu. Guru menampilkan kotak misterius dan bertanya: 'Apa yang ada di dalam kotak ini? Siapa yang ingin tahu?' Guru mengizinkan beberapa anak menebak. Setelah semua menebak, guru membuka kotak dan menunjukkan isinya. Guru bertanya: 'Mengapa kalian ingin tahu isinya? Apa yang kalian rasakan ketika bertanya?' Guru memperkenalkan tema: 'Pertanyaan adalah kunci untuk belajar! Hari ini kita akan belajar mengajukan pertanyaan yang hebat!'",
      inti: [
        "KATA TANYA 5W1H: Guru memperkenalkan kata tanya dasar: APA, SIAPA, KAPAN, DI MANA, MENGAPA, BAGAIMANA. Guru memberikan contoh untuk setiap kata tanya: (APA: Apa nama hewan ini?, SIAPA: Siapa yang menemukan?, KAPAN: Kapan itu terjadi?, DI MANA: Di mana hewan itu hidup?, MENGAPA: Mengapa hewan itu punya ciri ini?, BAGAIMANA: Bagaimana hewan itu bergerak?). Anak mempraktikkan membuat pertanyaan dengan setiap kata tanya.",
        "PERTANYAAN BAIK VS KURANG BAIK: Guru menampilkan dua jenis pertanyaan dan meminta anak menilai mana yang lebih baik. Contoh: (Kurang baik: 'Hewan ini apa?' vs Baik: 'Apa nama hewan ini dan di mana ia hidup?'), (Kurang baik: 'Kenapa?' vs Baik: 'Mengapa hewan ini punya warna cerah?'). Anak berdiskusi: Apa yang membuat pertanyaan kedua lebih baik? (lebih spesifik, lebih jelas, lebih lengkap).",
        "GAME TEBAK PERTANYAAN: Guru menampilkan gambar benda atau hewan. Anak dibagi menjadi kelompok. Setiap kelompok harus membuat pertanyaan sebaik mungkin tentang gambar tersebut. Setiap kelompok membacakan pertanyaan mereka, dan kelompok lain menilai kualitas pertanyaan (skala 1-5). Kelompok dengan skor tertinggi menang.",
        "PRAKTIK MENGAJUKAN PERTANYAAN: Guru membawa benda misterius baru atau menampilkan gambar menarik. Anak diminta mengajukan pertanyaan sebaik mungkin tentang benda tersebut. Guru mencatat semua pertanyaan di papan dan kemudian mengajak anak mengevaluasi: Pertanyaan mana yang paling spesifik? Mana yang paling menarik? Mana yang paling penting?",
        "SQC (SOMEBODY WANTED BUT SO THEN): Guru mengajarkan teknik SQC untuk membuat pertanyaan dari cerita: (SOMEBODY: Siapa tokohnya?, WANTED: Apa yang diinginkan tokoh?, BUT: Apa yang menghalangi?, SO THEN: Apa yang terjadi kemudian?). Guru membacakan cerita singkat, dan anak membuat pertanyaan berdasarkan teknik ini.",
        "PENCARIAN JAWABAN: Setelah anak mengajukan pertanyaan, guru mengajak anak mencari jawaban bersama. Guru menunjukkan berbagai sumber jawaban: (buku, internet, orang lain, eksperimen). Anak mempraktikkan mencari jawaban untuk salah satu pertanyaan mereka menggunakan sumber yang tersedia."
      ],
      penutup: "Guru mengajak anak duduk melingkar. Guru memilih beberapa pertanyaan terbaik yang diajukan anak hari ini dan membacakan kembali. Guru memberikan apresiasi khusus kepada anak-anak yang mengajukan pertanyaan berkualitas. Guru mengatakan: 'Pertanyaan kalian semua hebat! Teruslah bertanya, karena bertanya adalah cara menjadi pintar!' Guru memberikan 'Sertifikat Penanya Cilik' atau 'Bintang Keingintahuan' kepada setiap anak dengan catatan khusus (misalnya: 'Pertanyaan yang paling kreatif', 'Pertanyaan yang paling mendalam'). Guru memimpin doa agar selalu diberikan rasa ingin tahu dan keberanian bertanya, kemudian menutup dengan ajakan: 'Jangan pernah berhenti bertanya! Setiap pertanyaan membawa kalian ke pengetahuan baru!'",
    },
    lampiran: "Lampiran 1: Kotak misterius dan benda-benda menarik. Lampiran 2: Gambar-gambar untuk game tebak pertanyaan. Lampiran 3: Poster kata tanya 5W1H. Lampiran 4: Rubrik penilaian kualitas pertanyaan. Lampiran 5: Sertifikat Penanya Cilik. Lampiran 6: Buku sumber untuk mencari jawaban. Lampiran 7: Contoh cerita untuk teknik SQC."
  }
]

async function main() {
  console.log('Seeding 15 KBC Templates...')
  
  for (const template of kbcTemplates) {
    await db.rPPTemplate.upsert({
      where: { tema: template.tema },
      update: {
        kelompokUsia: template.kelompokUsia,
        topikKBC: template.topikKBC,
        tujuanKBC: template.tujuanKBC,
        tujuanProfilLulusan: template.tujuanProfilLulusan,
        tujuanPembelajaranMendalam: template.tujuanPembelajaranMendalam,
        kerangkaPembelajaran: template.kerangkaPembelajaran,
        kegiatanPembelajaran: template.kegiatanPembelajaran,
        lampiran: template.lampiran
      },
      create: template
    })
    console.log(`✓ Template "${template.tema}" (Topik: ${template.topikKBC})`)
  }
  
  console.log('✓ All 15 KBC templates seeded successfully!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
